import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, realpathSync, renameSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { createId } from "@nosh/core";
import { ArtifactStore, type Artifact } from "@nosh/evidence";
import { GitWorkspaceManager } from "@nosh/git-workspaces";
import { ExperimentTree } from "@nosh/graph";
import { loadNativeEvaluation, type JobRecord, type JobSpec, type JobSupervisor } from "@nosh/jobs";
import type { RegisteredProject } from "@nosh/persistence";
import type { PiAdapter, PiSessionOptions } from "@nosh/pi-adapter";
import type { OrchestrationRuntime } from "@nosh/orchestration-runtime";
import { canonicalJson, schemaUri, sha256, validateRecord, type EventDraft, type JsonValue, type TaskPermissions } from "@nosh/wire";
import type { AutoresearchBudgetUse, AutoresearchProjection, ResearchControl, Stored } from "./research-control.js";
import { validateGitCompletion } from "./task-postflight.js";

type Contract = { primaryMetric: { name: string; objective: "maximize" | "minimize"; minimumEffect: number }; baselineMetrics: Record<string, number>; roundWidths?: number[]; stopConditions?: { target?: number; maximumNoProgressRounds?: number }; execution: { runner: "native" | "wsl2"; distribution?: string | null; command: string[]; resultPath: string; timeoutSeconds: number; checkpointCommand?: string[] | null; usesGpu?: boolean } };
type Proposal = { $schema: string; proposalId: string; autoresearchId: string; experimentId: string; parentExperimentId: string; round: number; hypothesis: string; rationale: string; primaryChange: { category: string; description: string; expectedFiles: string[] }; novelty: { ideaFingerprint: string }; evaluationContractHash: string; proposedByAgentId: string; submittedAt: string };
type RunManifest = { $schema: string; runId: string; experimentId: string; evaluationContractHash: string; evaluatedCommit: string; resolvedCommand: string[]; workingDirectory: string; configurationArtifactId: string; environmentManifestArtifactId: string; jobId: string; startedAt: string };
type ExperimentResult = { $schema: string; autoresearchId: string; experimentId: string; parentExperimentId: string; branch: string; evaluatedCommit: string; evaluationContractHash: string; runIds: string[]; metrics: JsonValue[]; comparison: { parentScore: number; candidateScore: number | null; improvement: number | null; minimumEffect: number }; deterministicValidation: "pass" | "fail"; reviewId: string | null; reviewVerdict: string | null; promotionRecommendation: "promote" | "hold" | "reject"; promotionDecision: "promoted" | "held" | "rejected"; artifactIds: string[]; attemptFingerprint: string; completedAt: string };
type ReviewRequest = { $schema: string; reviewRequestId: string; reviewId: string; reviewType: "experiment" | "experiment_round" | "autoresearch_closure"; target: { targetType: string; targetId: string; targetVersion: number }; reviewerAgentId: string; criteria: Array<{ criterionId: string; required: boolean }>; requiredArtifactIds: string[]; requiredEvidenceIds: string[] };
type ReviewVerdict = { $schema?: string; reviewId?: string; reviewRequestId?: string; reviewType?: string; target?: { targetType?: string; targetId?: string; targetVersion?: number }; reviewerAgentId?: string; independenceCheck?: string; verdict?: string; criteria?: Array<{ criterionId?: string; status?: string }>; reviewedArtifactIds?: string[]; reviewedEvidenceIds?: string[] };

export class AutoresearchSupervisor {
  private timer: NodeJS.Timeout | undefined; private readonly busy = new Set<string>();
  constructor(private readonly research: ResearchControl, private readonly agents: PiAdapter, private readonly jobs: JobSupervisor, private readonly startJob: (spec: JobSpec) => JobRecord, private readonly projects: () => RegisteredProject[], private readonly packagePath: string, private readonly emit: (draft: EventDraft) => void, private readonly runtime?: OrchestrationRuntime) {}
  start(): void { this.timer = setInterval(() => void this.tick(), 1_000); this.timer.unref(); }
  stop(): void { if (this.timer) clearInterval(this.timer); this.timer = undefined; }
  async tick(): Promise<void> { for (const project of this.projects()) for (const execution of this.research.autoresearch(project.projectId)) if (execution.state === "running") await this.cycle(project, execution.entityId); }

  private async cycle(project: RegisteredProject, autoresearchId: string): Promise<void> {
    if (this.busy.has(autoresearchId) || this.agents.inspect().some((agent) => agent.autoresearchId === autoresearchId)) return; const current = this.research.autoresearchExecution(project.projectId, autoresearchId); if (this.runtime?.hasActiveFork(project.projectId, current.value.missionId, current.value.directionId)) return; this.busy.add(autoresearchId);
    try {
      let execution = this.research.autoresearchExecution(project.projectId, autoresearchId); const contract = parseContract(execution.value.evaluationContract); const records = this.records(project.projectId, autoresearchId);
      const completion = records.find((record) => record.$schema === schemaUri("autoresearch-completion-packet")); if (completion) { this.research.transitionAutoresearch(project.projectId, autoresearchId, execution.version, "completed", `autoresearch-completed:${autoresearchId}`); return; }
      const round = [...records].reverse().find((record) => record.$schema === schemaUri("autoresearch-round") && validateRecord(schemaUri("autoresearch-round"), record as unknown as JsonValue).ok);
      if (round && typeof round.round === "number" && Number.isInteger(round.round)) {
        const promoted = Array.isArray(round.promotedExperimentIds) ? round.promotedExperimentIds.filter((id): id is string => typeof id === "string") : [];
        const focusCheck = round.focusCheck as { action?: unknown } | undefined;
        const stopRequested = focusCheck?.action === "stop" && promoted.length === 0;
        if (round.round > execution.value.currentRound) {
          execution = this.research.advanceAutoresearch(project.projectId, autoresearchId, execution.version, round.round, promoted.length ? promoted : execution.value.acceptedFrontierExperimentIds, `autoresearch-round-projection:${autoresearchId}:${round.round}`);
        }
        if (stopRequested && round.round === execution.value.currentRound) {
          const terminalReason = execution.value.acceptedFrontierExperimentIds.length ? "evidence_saturation" : "all_hypotheses_rejected";
          await this.close(project, execution, this.records(project.projectId, autoresearchId), terminalReason);
          return;
        }
      }
      const pendingRun = (records.filter((record) => record.$schema === schemaUri("run-manifest")) as unknown as RunManifest[]).find((run) => !records.some((record) => record.$schema === schemaUri("job-result") && (record as { runId?: string }).runId === run.runId));
      if (pendingRun) { let job: JobRecord; try { job = this.jobs.get(pendingRun.jobId); } catch { const environment = new ArtifactStore(join(project.repositoryRoot, ".nosh", "artifacts")).resolve(pendingRun.environmentManifestArtifactId); job = this.startJob({ jobId: pendingRun.jobId, projectId: project.projectId, missionId: execution.value.missionId, directionId: execution.value.directionId, autoresearchId: execution.entityId, runId: pendingRun.runId, experimentId: pendingRun.experimentId, commitSha: pendingRun.evaluatedCommit, workingDirectory: pendingRun.workingDirectory, runner: contract.execution.runner, distribution: contract.execution.distribution ?? null, command: pendingRun.resolvedCommand, checkpointCommand: contract.execution.checkpointCommand ?? null, environmentLockHash: environment.contentHash, evaluationContractHash: execution.value.evaluationContractHash, timeoutSeconds: contract.execution.timeoutSeconds, usesGpu: contract.execution.usesGpu ?? false }); } if (["completed", "failed", "cancelled", "lost"].includes(job.state)) await this.finishRun(project, execution, contract, pendingRun, job); return; }
      const results = uniqueResults(records); const use = this.research.autoresearchBudgetUse(project.projectId, autoresearchId); const exhausted = [use.experiments >= execution.value.maximumExperiments ? "experiments" : null, use.rounds >= execution.value.maximumRounds ? "rounds" : null, use.modelTokens >= execution.value.maximumModelTokens ? "model_tokens" : null, use.wallClockSeconds >= execution.value.maximumWallClockSeconds ? "wall_clock" : null, use.gpuSeconds > execution.value.maximumGpuSeconds || Boolean(contract.execution.usesGpu) && use.gpuSeconds >= execution.value.maximumGpuSeconds ? "gpu_seconds" : null, use.diskBytes >= execution.value.maximumDiskBytes ? "disk_bytes" : null].filter((value): value is string => Boolean(value)); if (exhausted.length) { this.emit(event(execution.value, "autoresearch.budget_exhausted", { exhausted, use: use as unknown as JsonValue })); if (results.length) await this.close(project, execution, records, "budget_exhausted", use); else this.research.transitionAutoresearch(project.projectId, autoresearchId, execution.version, "blocked", `autoresearch-budget-blocked:${autoresearchId}`); return; }
      await this.startExperiment(project, execution, contract, records);
    } catch (error) { const execution = this.research.autoresearchExecution(project.projectId, autoresearchId); this.emit(event(execution.value, "autoresearch.supervisor_error", { message: error instanceof Error ? error.message : "Autoresearch supervisor failed" })); if (execution.state === "running") this.research.transitionAutoresearch(project.projectId, autoresearchId, execution.version, "blocked", `autoresearch-blocked:${createId("cmd")}`); }
    finally { this.busy.delete(autoresearchId); }
  }

  private async startExperiment(project: RegisteredProject, execution: Stored<AutoresearchProjection>, contract: Contract, records: Record<string, unknown>[]): Promise<void> {
    const results = uniqueResults(records); const proposals = records.filter((record) => record.$schema === schemaUri("experiment-proposal")) as unknown as Proposal[]; const pending = proposals.find((proposal) => !results.some((result) => result.experimentId === proposal.experimentId) && !records.some((record) => record.$schema === schemaUri("run-manifest") && (record as { experimentId?: string }).experimentId === proposal.experimentId)); const ordinal = results.length + 1; const widths = roundWidths(execution.value, contract); const round = pending?.round ?? roundAt(ordinal, widths); const parentExperimentId = pending?.parentExperimentId ?? (round === 1 ? execution.value.rootExperimentId : execution.value.acceptedFrontierExperimentIds[0] ?? execution.value.rootExperimentId); if (!parentExperimentId) throw new Error("Autoresearch has no accepted parent frontier"); const parentCommit = parentExperimentId === execution.value.rootExperimentId ? this.rootCommit(project, execution) : results.find((result) => result.experimentId === parentExperimentId)?.evaluatedCommit; if (!parentCommit) throw new Error("Experiment parent commit is unresolved");
    let proposal = pending; if (!proposal) { const experimentId = createId("exp"); const proposalAgent = createId("agt"); const taskId = createId("tsk"); await this.session(project, execution.value, { agentId: proposalAgent, taskId, experimentId, role: "general_worker", cwd: project.repositoryRoot }, `Propose one bounded experiment for ${execution.value.decisionQuestion}. Submit exactly one ${schemaUri("experiment-proposal")} with proposalId=proposal_${experimentId.slice(4)}, autoresearchId=${execution.entityId}, experimentId=${experimentId}, parentExperimentId=${parentExperimentId}, round=${round}, proposedByAgentId=${proposalAgent}, and evaluationContractHash=${execution.value.evaluationContractHash}. The idea fingerprint must be distinct from prior proposals.`); proposal = this.taskRecord(project.projectId, taskId, "experiment-proposal") as unknown as Proposal | undefined; if (!proposal || !validateRecord(schemaUri("experiment-proposal"), proposal as unknown as JsonValue).ok || proposal.autoresearchId !== execution.entityId || proposal.experimentId !== experimentId || proposal.parentExperimentId !== parentExperimentId || proposal.round !== round || proposal.proposedByAgentId !== proposalAgent || proposal.evaluationContractHash !== execution.value.evaluationContractHash) throw new Error("Worker did not submit the bounded experiment proposal"); }
    this.rehydrateTree(execution.value, records, parentCommit).add({ experimentId: proposal.experimentId, parentExperimentId: proposal.parentExperimentId, ideaFingerprint: proposal.novelty.ideaFingerprint, attemptFingerprint: sha256({ experimentId: proposal.experimentId, proposalId: proposal.proposalId }), evaluationContractHash: execution.value.evaluationContractHash, branch: branchName(execution.entityId, proposal.experimentId), evaluatedCommit: null, depth: round, state: "proposed", reviewId: null, reviewerAgentId: null, guardrailsPass: null });
    const manager = managerFor(project); const branch = branchName(execution.entityId, proposal.experimentId); const worktreeId = `wt_${proposal.experimentId.slice(4)}`; const createIntent = this.research.beginExternalOperation(project.projectId, "git.worktree.create", `git-worktree:${proposal.experimentId}`, { branch, baseCommit: parentCommit, worktreeId }); const worktree = manager.create(branch, parentCommit, worktreeId); this.research.completeExternalOperation(project.projectId, createIntent.intentId, { branch, worktree });
    const priorPacket = records.find((record) => record.$schema === schemaUri("task-packet") && (record as { scope?: { experimentId?: string } }).scope?.experimentId === proposal!.experimentId) as TaskPacket | undefined; const taskId = priorPacket?.taskId ?? createId("tsk"); const workerId = priorPacket?.assignedAgentId ?? proposal.proposedByAgentId; const packet = priorPacket ?? this.taskPacket(project, execution, proposal, taskId, workerId, branch, parentCommit); if (!priorPacket) this.submit(project, execution.value, `experiment:${proposal.experimentId}:implementation`, packet as unknown as JsonValue, `experiment-task-packet:${proposal.experimentId}`, workerId, proposal.experimentId);
    let completion = this.research.terminalRecord(project.projectId, taskId, "general-worker-completion"); if (!completion) { await this.session(project, execution.value, { agentId: workerId, taskId, experimentId: proposal.experimentId, role: "general_worker", cwd: worktree, taskPermissions: packet.permissions, taskWorkspace: packet.workspace }, `Acknowledge this Task Packet before work: ${JSON.stringify(packet)}. Then implement exactly one bounded variant for experiment ${proposal.experimentId}, variantOrdinal=${ordinal}. Commit the declared paths and submit exactly one ${schemaUri("general-worker-completion")}.`); completion = this.research.terminalRecord(project.projectId, taskId, "general-worker-completion"); }
    if (!this.acknowledged(project.projectId, taskId, packet) || !completion || postflight(worktree, packet, completion).length) throw new Error("Experiment implementation failed deterministic Task postflight");
    const environment = { node: process.version, platform: process.platform, arch: process.arch }; const freezeIntent = this.research.beginExternalOperation(project.projectId, "git.experiment.freeze", `git-freeze:${proposal.experimentId}`, { experimentId: proposal.experimentId, branch, parentCommit, evaluationContractHash: execution.value.evaluationContractHash, command: contract.execution.command }); const frozen = manager.freeze({ experimentId: proposal.experimentId, parentExperimentId: proposal.parentExperimentId, branch, worktree, parentCommit, evaluationContractHash: execution.value.evaluationContractHash, environmentManifest: environment, runCommand: contract.execution.command }); this.research.completeExternalOperation(project.projectId, freezeIntent.intentId, frozen as unknown as JsonValue);
    const stateRoot = join(project.repositoryRoot, ".nosh", "autoresearch", execution.entityId, proposal.experimentId); mkdirSync(stateRoot, { recursive: true }); const configurationPath = this.write(project.projectId, `configuration:${proposal.experimentId}`, join(stateRoot, "configuration.json"), execution.value.evaluationContract); const environmentPath = this.write(project.projectId, `environment:${proposal.experimentId}`, join(stateRoot, "environment.json"), environment); const configuration = this.artifact(project, execution.value, proposal.experimentId, "artifact_configuration", "application/json", configurationPath); const environmentArtifact = this.artifact(project, execution.value, proposal.experimentId, "artifact_environment", "application/json", environmentPath); const runId = createId("run"); const jobId = createId("job"); const startedAt = new Date().toISOString(); const run: JsonValue = { $schema: schemaUri("run-manifest"), schemaVersion: 1, runId, experimentId: proposal.experimentId, evaluationContractHash: execution.value.evaluationContractHash, evaluatedCommit: frozen.evaluatedCommit, seed: 0, resolvedCommand: contract.execution.command, workingDirectory: worktree, inputArtifactIds: [], configurationArtifactId: configuration.artifactId, environmentManifestArtifactId: environmentArtifact.artifactId, hardware: environment, jobId, state: "queued", metricArtifactId: null, requiredOutputArtifactIds: [], startedAt, finishedAt: null }; this.submit(project, execution.value, `run:${runId}`, run, `run-manifest:${runId}`, null, proposal.experimentId, runId, jobId); this.startJob({ jobId, projectId: project.projectId, missionId: execution.value.missionId, directionId: execution.value.directionId, autoresearchId: execution.entityId, runId, experimentId: proposal.experimentId, commitSha: frozen.evaluatedCommit, workingDirectory: worktree, runner: contract.execution.runner, distribution: contract.execution.distribution ?? null, command: contract.execution.command, checkpointCommand: contract.execution.checkpointCommand ?? null, environmentLockHash: environmentArtifact.contentHash, evaluationContractHash: execution.value.evaluationContractHash, timeoutSeconds: contract.execution.timeoutSeconds, usesGpu: contract.execution.usesGpu ?? false });
  }

  private async finishRun(project: RegisteredProject, execution: Stored<AutoresearchProjection>, contract: Contract, run: RunManifest, job: JobRecord): Promise<void> {
    const records = this.records(project.projectId, execution.entityId);
    const proposal = records.find((record) => record.$schema === schemaUri("experiment-proposal") && (record as { experimentId?: string }).experimentId === run.experimentId) as unknown as Proposal | undefined;
    if (!proposal) throw new Error("Run has no experiment proposal");
    const artifacts: Artifact[] = [];
    if (existsSync(job.stdoutPath)) artifacts.push(this.artifact(project, execution.value, run.experimentId, "artifact_stdout.log", "text/plain", job.stdoutPath, "negative_evidence"));
    if (existsSync(job.stderrPath)) artifacts.push(this.artifact(project, execution.value, run.experimentId, "artifact_stderr.log", "text/plain", job.stderrPath, "negative_evidence"));
    const worktree = realpathSync(run.workingDirectory);
    const resultPath = resolve(worktree, contract.execution.resultPath);
    if (relative(worktree, resultPath).startsWith("..")) throw new Error("Evaluation result path escapes the worktree");
    const jobState = job.state === "completed" ? "succeeded" : job.state === "cancelled" ? "cancelled" : job.state === "lost" ? "lost" : "failed";
    let metrics: JsonValue = { error: job.failureReason ?? jobState };
    let metric: Artifact | null = null;
    let metricFailure: string | null = jobState === "succeeded" ? "evaluation result file is absent" : `job ${jobState}`;
    if (jobState === "succeeded" && existsSync(resultPath)) {
      try {
        const loaded = loadNativeEvaluation(resultPath);
        if (!isMetricObject(loaded)) metricFailure = "evaluation result is not a JSON object";
        else {
          metrics = loaded;
          const primary = primaryMetric(metrics, contract.primaryMetric.name);
          metricFailure = primary.failure;
        }
      } catch (error) {
        metricFailure = error instanceof Error ? error.message : "evaluation result is malformed";
      }
      if (metricFailure) metrics = { error: metricFailure };
      metric = this.artifact(project, execution.value, run.experimentId, "artifact_metrics", "application/json", resultPath, metricFailure ? "negative_evidence" : "accepted_evidence");
      artifacts.push(metric);
    }
    const environment = new ArtifactStore(join(project.repositoryRoot, ".nosh", "artifacts")).resolve(run.environmentManifestArtifactId);
    const finishedAt = job.finishedAt ?? new Date().toISOString();
    const resultDigest = sha256({ state: jobState, metrics, exitCode: job.exitCode, metricFailure });
    const jobResult: JsonValue = { $schema: schemaUri("job-result"), schemaVersion: 1, jobId: job.jobId, runId: job.runId, experimentId: job.experimentId, state: jobState, commandDigest: job.commandDigest, evaluatedCommit: job.commitSha, environmentManifestArtifactId: environment.artifactId, startedAt: job.startedAt!, finishedAt, durationSeconds: Math.max(0, Math.floor((Date.parse(finishedAt) - Date.parse(job.startedAt!)) / 1000)), exit: { exitCode: job.exitCode, failureReason: job.failureReason ?? metricFailure }, resourceUse: { gpuSeconds: job.usesGpu ? Math.max(0, Math.floor((Date.parse(finishedAt) - Date.parse(job.startedAt!)) / 1000)) : 0 }, metricArtifactId: metric?.artifactId ?? null, logArtifactIds: artifacts.filter((artifact) => artifact.kind.includes("log")).map((artifact) => artifact.artifactId), checkpointArtifactIds: [], recovery: { recoveredAfterRestart: job.recoveredAfterRestart }, resultDigest };
    this.submit(project, execution.value, `run:${run.runId}`, jobResult, `job-result:${job.jobId}`, null, run.experimentId, run.runId, job.jobId);
    const parentScore = this.parentScore(execution.value, contract, proposal.parentExperimentId, records);
    const primary = primaryMetric(metrics, contract.primaryMetric.name);
    const candidateScore = primary.value;
    const improvement = candidateScore === null ? null : contract.primaryMetric.objective === "maximize" ? candidateScore - parentScore : parentScore - candidateScore;
    const deterministic = jobState === "succeeded" && metric !== null && primary.failure === null;
    const keep = deterministic && improvement !== null && improvement >= contract.primaryMetric.minimumEffect;
    const evidenceId = createId("evd");
    const failure = primary.failure ?? metricFailure;
    // Freeze the measured statement before Review. Only its review disposition may change.
    const candidateEvidence = { $schema: schemaUri("evidence"), schemaVersion: 1, evidenceId, projectId: project.projectId, evidenceType: keep ? "evidence_positive.result" : "evidence_negative.result", statement: keep ? `${proposal.experimentId} improved ${contract.primaryMetric.name} by ${improvement}.` : failure ? `${proposal.experimentId} produced an invalid evaluation result: ${failure}.` : `${proposal.experimentId} did not meet the ${contract.primaryMetric.name} keep rule.`, polarity: keep ? "supports" : "contradicts", sourceRefs: [{ refType: "source_experiment", refId: proposal.experimentId, locator: metric?.contentHash ?? resultDigest }], evaluationContractHash: execution.value.evaluationContractHash, scopeLimitations: ["Applies only to the frozen evaluation contract"], quality: { status: "unreviewed", reviewId: null, confidence: deterministic ? "high" : "low" }, createdBy: "agent", createdByAgentId: proposal.proposedByAgentId, createdAt: new Date().toISOString() };
    let request: ReviewRequest | null = null;
    let verdict: ReviewVerdict | undefined;
    if (deterministic) {
      const reviewerId = createId("agt");
      request = this.reviewRequest(project, execution.value, reviewerId, [proposal.proposedByAgentId], "experiment", "target_experiment", proposal.experimentId, 1, `criterion_${proposal.experimentId.slice(4)}`, `Validate the frozen parent comparison and guardrails for ${proposal.hypothesis}`, [metric!.artifactId], [evidenceId]);
      verdict = await this.reviewSession(project, execution.value, run.experimentId, reviewerId, request, `Review experiment ${proposal.experimentId}. Parent score=${parentScore}; candidate score=${candidateScore}; improvement=${improvement}. Review this candidate Evidence for publication with your exact disposition: ${JSON.stringify(candidateEvidence)}`);
    }
    const accepted = keep && verdict?.verdict === "PASS";
    const evidence: JsonValue = { ...candidateEvidence, quality: { ...candidateEvidence.quality, status: verdict ? "reviewed" : "unreviewed", reviewId: verdict ? request!.reviewId : null } };
    this.submit(project, execution.value, `experiment:${proposal.experimentId}`, evidence, `experiment-evidence:${proposal.experimentId}`, proposal.proposedByAgentId, proposal.experimentId, run.runId, job.jobId);
    const result: JsonValue = { $schema: schemaUri("experiment-result"), schemaVersion: 1, autoresearchId: execution.entityId, experimentId: proposal.experimentId, parentExperimentId: proposal.parentExperimentId, branch: branchName(execution.entityId, proposal.experimentId), evaluatedCommit: run.evaluatedCommit, evaluationContractHash: execution.value.evaluationContractHash, runIds: [run.runId], runSetStatus: deterministic ? "complete" : "invalid", metrics: [metrics], guardrails: [{ passed: deterministic, failure }], comparison: { parentScore, candidateScore, improvement, minimumEffect: contract.primaryMetric.minimumEffect }, deterministicValidation: deterministic ? "pass" : "fail", reviewId: request?.reviewId ?? null, reviewVerdict: verdict?.verdict ?? null, promotionRecommendation: accepted ? "promote" : "reject", promotionDecision: accepted ? "held" : "rejected", artifactIds: artifacts.map((artifact) => artifact.artifactId), attemptFingerprint: sha256({ proposalId: proposal.proposalId, evaluatedCommit: run.evaluatedCommit, contract: execution.value.evaluationContractHash }), completedAt: new Date().toISOString() };
    this.submit(project, execution.value, `experiment:${proposal.experimentId}`, result, `experiment-result:${proposal.experimentId}`, proposal.proposedByAgentId, proposal.experimentId, run.runId, job.jobId);
    const all = uniqueResults([...records, result as unknown as Record<string, unknown>]);
    const widths = roundWidths(execution.value, contract);
    if (roundBoundary(all.length, widths)) await this.finishRound(project, this.research.autoresearchExecution(project.projectId, execution.entityId), contract, proposal.round, all);
  }

  private async finishRound(project: RegisteredProject, execution: Stored<AutoresearchProjection>, contract: Contract, round: number, results: ExperimentResult[]): Promise<void> {
    const records = this.records(project.projectId, execution.entityId);
    const proposals = records.filter((record) => record.$schema === schemaUri("experiment-proposal") && record.round === round) as unknown as Proposal[];
    const roundResults = results.filter((result) => proposals.some((proposal) => proposal.experimentId === result.experimentId));
    const candidates = roundResults.filter((result) => result.promotionRecommendation === "promote" && result.deterministicValidation === "pass");
    const winner = candidates.sort((left, right) => score(right) - score(left))[0];
    const reviewerId = createId("agt");
    const evidenceIds = records.flatMap((record) => {
      if (record.$schema !== schemaUri("evidence") || !Array.isArray(record.sourceRefs) || !record.sourceRefs.some((source) => source && typeof source === "object" && "refId" in source && typeof source.refId === "string" && proposals.some((proposal) => proposal.experimentId === source.refId)) || typeof record.evidenceId !== "string") return [];
      return [record.evidenceId];
    });
    const request = this.reviewRequest(project, execution.value, reviewerId, proposals.map((proposal) => proposal.proposedByAgentId), "experiment_round", "target_experiment.round", `round_${execution.entityId.slice(3)}.${round}`, round, `criterion_round.${round}`, `Validate round ${round} sibling comparison and promotion`, roundResults.flatMap((result) => result.artifactIds), evidenceIds);
    const verdict = await this.reviewSession(project, execution.value, null, reviewerId, request, `Review Autoresearch round ${round}: ${JSON.stringify(roundResults)}`);
    let promoted: string[] = [];
    if (winner && verdict?.verdict === "PASS") {
      const manager = managerFor(project);
      const base = this.rootCommit(project, execution);
      const integrationBranch = `ar/${execution.entityId.slice(3, 11)}/integration`;
      const integrationId = `integration_${execution.entityId.slice(3)}`;
      const worktreeIntent = this.research.beginExternalOperation(project.projectId, "git.worktree.create", `git-integration:${execution.entityId}`, { branch: integrationBranch, baseCommit: base, worktreeId: integrationId });
      const integration = manager.create(integrationBranch, base, integrationId);
      this.research.completeExternalOperation(project.projectId, worktreeIntent.intentId, { branch: integrationBranch, worktree: integration });
      const promoteIntent = this.research.beginExternalOperation(project.projectId, "git.experiment.promote", `git-promote:${winner.experimentId}`, { experimentId: winner.experimentId, integration, evaluationContractHash: execution.value.evaluationContractHash });
      const head = manager.promote(winner.experimentId, integration, "PASS", true);
      this.research.completeExternalOperation(project.projectId, promoteIntent.intentId, { experimentId: winner.experimentId, integrationHead: head });
      const promotedResult = { ...winner, promotionDecision: "promoted" } as unknown as JsonValue;
      this.submit(project, execution.value, `experiment:${winner.experimentId}`, promotedResult, `experiment-result-promoted:${winner.experimentId}`, null, winner.experimentId);
      promoted = [winner.experimentId];
    }
    const manager = managerFor(project);
    const currentRecords = this.research.submitted(project.projectId);
    for (const result of roundResults) {
      const proposal = proposals.find((entry) => entry.experimentId === result.experimentId);
      if (!proposal) throw new Error("Round result has no proposal");
      const frozen = manager.assertFrozen(result.experimentId, result.evaluatedCommit, execution.value.evaluationContractHash);
      const resultEntry = [...currentRecords].reverse().find((entry) => {
        const record = entry.record;
        return entry.event.scope.autoresearchId === execution.entityId && record && typeof record === "object" && !Array.isArray(record) && record.$schema === schemaUri("experiment-result") && record.experimentId === result.experimentId;
      });
      const sequence = resultEntry?.event.sequence ?? 0;
      const accepted = promoted.includes(result.experimentId);
      const manifest: JsonValue = { $schema: schemaUri("experiment-manifest"), schemaVersion: 1, experimentId: result.experimentId, autoresearchId: execution.entityId, proposalId: proposal.proposalId, parentExperimentId: result.parentExperimentId, treeDepth: round, round, hypothesis: proposal.hypothesis, primaryChange: proposal.primaryChange, ideaFingerprint: proposal.novelty.ideaFingerprint, attemptFingerprint: result.attemptFingerprint, branch: result.branch, worktreeId: `wt_${result.experimentId.slice(4)}`, parentCommit: frozen.parentCommit, implementationCommit: frozen.evaluatedCommit, evaluatedCommit: frozen.evaluatedCommit, evaluationContractHash: execution.value.evaluationContractHash, state: accepted ? "accepted" : "rejected", runIds: result.runIds, resultRecordSequence: sequence, reviewId: accepted ? request.reviewId : result.reviewId, promotionDecision: accepted ? "promoted" : "rejected", artifactIds: result.artifactIds, createdAt: proposal.submittedAt, evaluatedAt: result.completedAt };
      this.submit(project, execution.value, `experiment:${result.experimentId}`, manifest, `experiment-manifest:${result.experimentId}`, null, result.experimentId);
    }
    const noProgressCount = promoted.length ? 0 : noProgressRounds(records) + 1;
    const focusAction = !promoted.length && noProgressCount >= (contract.stopConditions?.maximumNoProgressRounds ?? 1) ? "stop" : "continue";
    const roundRecord: JsonValue = { $schema: schemaUri("autoresearch-round"), schemaVersion: 1, autoresearchId: execution.entityId, round, inputFrontierExperimentIds: round === 1 ? [execution.value.rootExperimentId] : execution.value.acceptedFrontierExperimentIds, proposedExperimentIds: proposals.map((proposal) => proposal.experimentId), evaluatedExperimentIds: roundResults.map((result) => result.experimentId), promotedExperimentIds: promoted, rejectedExperimentIds: roundResults.filter((result) => !promoted.includes(result.experimentId)).map((result) => result.experimentId), progressDelta: { reviewedExperiments: roundResults.length, promoted: promoted.length }, focusCheck: { distinctIdeaFamiliesInWindow: new Set(proposals.map((proposal) => proposal.novelty.ideaFingerprint)).size, repeatedFingerprintCount: proposals.length - new Set(proposals.map((proposal) => proposal.novelty.ideaFingerprint)).size, noProgressCount, action: focusAction }, reviewId: request.reviewId, nextRoundPurpose: focusAction === "stop" ? "Stop because no candidate passed" : promoted.length ? "Descend from the reviewed winner" : "Continue bounded search after no promotion", completedAt: new Date().toISOString() };
    this.submit(project, execution.value, `autoresearch:${execution.entityId}`, roundRecord, `autoresearch-round:${execution.entityId}:${round}`, reviewerId);
    const frontier = promoted.length ? promoted : execution.value.acceptedFrontierExperimentIds;
    const advanced = this.research.advanceAutoresearch(project.projectId, execution.entityId, execution.version, round, frontier, `autoresearch-round-projection:${execution.entityId}:${round}`);
    if (focusAction === "stop") {
      const reason = frontier.length ? "evidence_saturation" : "all_hypotheses_rejected";
      await this.close(project, advanced, this.records(project.projectId, execution.entityId), reason);
      return;
    }
    const target = contract.stopConditions?.target;
    const scoreAtTarget = winner?.comparison.candidateScore;
    const targetReached = target !== undefined && scoreAtTarget !== null && scoreAtTarget !== undefined && (contract.primaryMetric.objective === "maximize" ? scoreAtTarget >= target : scoreAtTarget <= target);
    if (promoted.length && targetReached) await this.close(project, advanced, this.records(project.projectId, execution.entityId), "target_reached");
  }

  private async close(project: RegisteredProject, execution: Stored<AutoresearchProjection>, records: Record<string, unknown>[], terminalReason: "target_reached" | "budget_exhausted" | "evidence_saturation" | "all_hypotheses_rejected", budgetUse?: AutoresearchBudgetUse): Promise<void> {
    const results = uniqueResults(records);
    const evidenceIds = records.flatMap((record) => record.$schema === schemaUri("evidence") && typeof record.evidenceId === "string" ? [record.evidenceId] : []);
    if (!results.length || !evidenceIds.length) throw new Error("Autoresearch cannot close without evaluated experiments and Evidence");
    const root = join(project.repositoryRoot, ".nosh", "autoresearch", execution.entityId);
    const synthesisPath = this.write(project.projectId, `synthesis:${execution.entityId}`, join(root, "synthesis.json"), { decisionQuestion: execution.value.decisionQuestion, results, frontier: execution.value.acceptedFrontierExperimentIds, terminalReason });
    const synthesis = this.artifact(project, execution.value, null, "artifact_synthesis", "application/json", synthesisPath);
    const producers = records.flatMap((record) => record.$schema === schemaUri("experiment-proposal") && typeof record.proposedByAgentId === "string" ? [record.proposedByAgentId] : []);
    const reviewerId = createId("agt");
    const request = this.reviewRequest(project, execution.value, reviewerId, producers, "autoresearch_closure", "target_autoresearch", execution.entityId, execution.version, `criterion_${execution.entityId.slice(3)}`, execution.value.decisionQuestion, [synthesis.artifactId], evidenceIds);
    const verdict = await this.reviewSession(project, execution.value, null, reviewerId, request, `Review Autoresearch closure for ${execution.value.decisionQuestion}.`);
    if (verdict?.verdict !== "PASS") throw new Error("Autoresearch closure Review did not pass");
    const best = execution.value.acceptedFrontierExperimentIds.find((id) => results.some((result) => result.experimentId === id && result.promotionDecision === "promoted")) ?? null;
    const runs = records.flatMap((record) => record.$schema === schemaUri("run-manifest") && typeof record.runId === "string" ? [record.runId] : []);
    const use = budgetUse ?? this.research.autoresearchBudgetUse(project.projectId, execution.entityId);
    const completion: JsonValue = { $schema: schemaUri("autoresearch-completion-packet"), schemaVersion: 1, completionPacketId: `completion_${execution.entityId.slice(3)}`, autoresearchId: execution.entityId, directionId: execution.value.directionId, evaluationContractHash: execution.value.evaluationContractHash, terminalReason, budgetUse: use as unknown as JsonValue, tree: { rootExperimentId: execution.value.rootExperimentId, evaluatedExperimentIds: results.map((result) => result.experimentId), acceptedFrontierExperimentIds: execution.value.acceptedFrontierExperimentIds }, decisionAnswer: best ? `Reviewed experiment ${best} is the accepted frontier.` : "No tested experiment met the keep rule.", bestExperimentId: best, evidenceIds, failedHypothesisIds: results.filter((result) => result.promotionRecommendation === "reject").map((result) => result.experimentId), unresolvedQuestions: [], synthesisArtifactId: synthesis.artifactId, deterministicValidation: { status: "pass", validatorRunIds: runs }, closureReviewId: request.reviewId, completedAt: new Date().toISOString() };
    this.submit(project, execution.value, `autoresearch:${execution.entityId}`, completion, `autoresearch-completion:${execution.entityId}`, reviewerId);
    this.research.transitionAutoresearch(project.projectId, execution.entityId, execution.version, "completed", `autoresearch-completed:${execution.entityId}`);
  }

  private rehydrateTree(execution: AutoresearchProjection, records: Record<string, unknown>[], rootCommit: string): ExperimentTree { const tree = new ExperimentTree(execution.evaluationContractHash, execution.maximumDepth, execution.maximumChildrenPerParent); tree.add({ experimentId: execution.rootExperimentId, parentExperimentId: null, ideaFingerprint: sha256({ root: execution.rootExperimentId }), attemptFingerprint: sha256({ commit: rootCommit }), evaluationContractHash: execution.evaluationContractHash, branch: "baseline", evaluatedCommit: rootCommit, depth: 0, state: "accepted", reviewId: null, reviewerAgentId: null, guardrailsPass: true }); const proposals = records.filter((record) => record.$schema === schemaUri("experiment-proposal")) as unknown as Proposal[]; for (const result of uniqueResults(records).sort((a, b) => (proposals.find((proposal) => proposal.experimentId === a.experimentId)?.round ?? 0) - (proposals.find((proposal) => proposal.experimentId === b.experimentId)?.round ?? 0))) { const proposal = proposals.find((entry) => entry.experimentId === result.experimentId); if (!proposal) continue; tree.add({ experimentId: result.experimentId, parentExperimentId: result.parentExperimentId, ideaFingerprint: proposal.novelty.ideaFingerprint, attemptFingerprint: result.attemptFingerprint, evaluationContractHash: execution.evaluationContractHash, branch: result.branch, evaluatedCommit: null, depth: proposal.round, state: "proposed", reviewId: null, reviewerAgentId: null, guardrailsPass: null }); const review = records.find((record) => record.$schema === schemaUri("review-verdict") && (record as { reviewId?: string }).reviewId === result.reviewId) as { reviewerAgentId?: string; verdict?: string } | undefined; tree.evaluate(result.experimentId, result.evaluatedCommit, result.promotionRecommendation === "promote" ? "accepted" : "rejected", review?.reviewerAgentId && result.reviewId ? { reviewId: result.reviewId, reviewerAgentId: review.reviewerAgentId, verdict: review.verdict ?? "BLOCKED" } : null, result.deterministicValidation === "pass"); } return tree; }
  private rootCommit(project: RegisteredProject, execution: Stored<AutoresearchProjection> | AutoresearchProjection): string { const value = "value" in execution ? execution.value : execution; if (value.directionId) { const baseline = this.research.direction(project.projectId, value.directionId).value.acceptedBaseline?.commit; if (!baseline) throw new Error("Direction baseline is unresolved"); return git(project.repositoryRoot, ["rev-parse", `${baseline}^{commit}`]); } return git(project.repositoryRoot, ["rev-parse", "HEAD"]); }
  private parentScore(execution: AutoresearchProjection, contract: Contract, parentId: string, records: Record<string, unknown>[]): number { if (parentId === execution.rootExperimentId) return Number(contract.baselineMetrics[contract.primaryMetric.name] ?? 0); const parent = uniqueResults(records).find((result) => result.experimentId === parentId); if (!parent) throw new Error("Parent result is unresolved"); return metricValue(parent.metrics[0] ?? {}, contract.primaryMetric.name); }
  private records(projectId: string, autoresearchId: string): Record<string, unknown>[] { return this.research.submitted(projectId).filter((entry) => entry.event.scope.autoresearchId === autoresearchId).map((entry) => entry.record as unknown as Record<string, unknown>); }
  private taskRecord(projectId: string, taskId: string, schema: string): JsonValue | undefined { return this.research.submitted(projectId, `task:${taskId}`).find((entry) => (entry.record as { $schema?: string }).$schema === schemaUri(schema))?.record; }
  private submit(project: RegisteredProject, execution: AutoresearchProjection, correlationId: string, record: JsonValue, idempotencyKey: string, agentId: string | null, experimentId: string | null = null, runId: string | null = null, jobId: string | null = null) { return this.research.submitDaemonRecord(project.projectId, { projectId: project.projectId, missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId, experimentId, runId, jobId, agentId }, correlationId, record, idempotencyKey); }
  private taskPacket(project: RegisteredProject, execution: Stored<AutoresearchProjection>, proposal: Proposal, taskId: string, agentId: string, branch: string, startingCommit: string): TaskPacket {
    const now = Date.now();
    return {
      $schema: schemaUri("task-packet"), schemaVersion: 1, templateVersion: "1.0.0",
      taskId, attempt: 1, taskType: "task_experiment.implementation", assignedRole: "general_worker", assignedAgentId: agentId,
      scope: { projectId: project.projectId, missionId: execution.value.missionId, directionId: execution.value.directionId, autoresearchId: execution.entityId, experimentId: proposal.experimentId, graphNodeId: `experiment_${proposal.experimentId.slice(4)}` },
      goalStack: { projectGoalId: project.projectId, projectGoalSummary: execution.value.decisionQuestion, missionCriterionIds: execution.value.missionId ? [execution.value.missionId] : [], missionCriterionSummary: execution.value.decisionQuestion, directionQuestionId: execution.value.directionId ? `question_${execution.value.directionId.slice(4)}` : null, directionQuestionSummary: execution.value.directionId ? execution.value.decisionQuestion : null, nodeObjective: proposal.hypothesis },
      whyNow: `Round ${proposal.round} selected a distinct bounded hypothesis.`,
      instructions: [proposal.primaryChange.description, "Create commits only with nosh_git_commit and explicit changed paths.", "Report the exact immutable Git commit"],
      inScope: execution.value.scope.length ? execution.value.scope : ["**"], outOfScope: [".nosh/**"], inputArtifactIds: [], inputEvidenceIds: [],
      requiredOutputs: [{ outputId: `output_${proposal.experimentId.slice(4)}`, kind: "output_code.commit", required: true }],
      acceptanceCriteria: [{ criterionId: `criterion_${proposal.experimentId.slice(4)}`, statement: proposal.hypothesis, validatorIds: ["validator_git.postflight"], reviewRubricIds: ["rubric_experiment.correctness"], required: true }],
      workspace: { worktreeId: `wt_${proposal.experimentId.slice(4)}`, branch, startingCommit, writeScopes: execution.value.scope.length ? execution.value.scope : ["**"], protectedScopes: [".nosh/**"] },
      permissions: { network: "disabled", subprocess: "disabled", gitCommit: true, gitPush: false, delegation: "request_only", networkAllowlist: [], allowedToolIds: ["tool_nosh.task.acknowledge", "tool_nosh.response.submit", "tool_nosh.progress.emit", "tool_nosh.blocker.submit", "tool_nosh.delegation.request", "tool_pi.read", "tool_pi.edit", "tool_pi.write", "tool_nosh.git.commit"] },
      budget: { deadline: new Date(now + 7_200_000).toISOString(), maximumWallClockSeconds: 7_200, maximumModelTokens: Math.min(60_000, execution.value.maximumModelTokens), maximumToolCalls: 100, maximumRepairAttempts: 1 },
      progressPolicy: { milestoneIntervalSeconds: 900, emitOnFirstDurableDelta: true, emitOnBlocker: true, emitOnAnomaly: true, maximumSilentSeconds: 1_200 },
      responseSchema: schemaUri("general-worker-completion"), observedVersions: { autoresearchProjectionVersion: execution.version, round: proposal.round },
      lease: { leaseId: taskId, expiresAt: new Date(now + 7_200_000).toISOString(), heartbeatSeconds: 15 }, issuedBy: "research_director", issuedAt: new Date().toISOString(),
    };
  }
  private acknowledged(projectId: string, taskId: string, packet: TaskPacket): boolean { const ack = this.taskRecord(projectId, taskId, "task-acknowledgement") as { taskId?: string; attempt?: number; agentId?: string; decision?: string; understoodOutputIds?: string[]; understoodCriterionIds?: string[]; observedLeaseId?: string; observedStartingCommit?: string } | undefined; return Boolean(ack && validateRecord(schemaUri("task-acknowledgement"), ack as unknown as JsonValue).ok && ack.taskId === taskId && ack.attempt === packet.attempt && ack.agentId === packet.assignedAgentId && ack.decision === "accepted" && same(ack.understoodOutputIds, packet.requiredOutputs.map((output) => output.outputId)) && same(ack.understoodCriterionIds, packet.acceptanceCriteria.map((criterion) => criterion.criterionId)) && ack.observedLeaseId === packet.lease.leaseId && ack.observedStartingCommit === packet.workspace.startingCommit); }
  private reviewRequest(project: RegisteredProject, execution: AutoresearchProjection, reviewerAgentId: string, producers: string[], reviewType: ReviewRequest["reviewType"], targetType: string, targetId: string, targetVersion: number, criterionId: string, statement: string, artifacts: string[], evidence: string[]): ReviewRequest { const producerAgentIds = [...new Set(producers)]; if (!producerAgentIds.length || producerAgentIds.includes(reviewerAgentId)) throw new Error("Review requires an independent producer"); const reviewId = createId("rev"); const request = { $schema: schemaUri("review-request"), schemaVersion: 1, reviewRequestId: `request_${reviewId.slice(4)}`, reviewId, reviewType, target: { targetType, targetId, targetVersion }, scope: { projectId: project.projectId, missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId }, producerAgentIds, reviewerAgentId, independenceCheck: "pass", contractRefs: [{ kind: "contract_evaluation", id: `contract_${execution.autoresearchId.slice(3)}`, hash: execution.evaluationContractHash }], requiredArtifactIds: [...new Set(artifacts)], requiredEvidenceIds: [...new Set(evidence)], deterministicPostflight: { status: "pass", validatorRunIds: ["validator_experiment.postflight"] }, criteria: [{ criterionId, statement, required: true, severityIfFailed: "blocking" }], allowedVerdicts: ["PASS", "REVISE", "REDESIGN", "BLOCKED"], issuedAt: new Date().toISOString() } as unknown as ReviewRequest; this.submit(project, execution, `review:${reviewId}`, request as unknown as JsonValue, `review-request:${reviewId}`, reviewerAgentId); return request; }
  private async reviewSession(project: RegisteredProject, execution: AutoresearchProjection, experimentId: string | null, reviewerId: string, request: ReviewRequest, context: string): Promise<ReviewVerdict | undefined> { const taskId = createId("tsk"); await this.session(project, execution, { agentId: reviewerId, taskId, experimentId, role: "reviewer", cwd: project.repositoryRoot }, `${context} Review Request: ${JSON.stringify(request)}. Submit exactly one ${schemaUri("review-verdict")} with the exact Review Request identities.`); const review = this.research.terminalRecord(project.projectId, taskId, "review-verdict") as unknown as ReviewVerdict | undefined; return review && reviewPasses(review, request, reviewerId) ? review : undefined; }
  private async session(project: RegisteredProject, execution: AutoresearchProjection, input: { agentId: string; taskId: string; experimentId: string | null; role: PiSessionOptions["role"]; cwd: string; taskPermissions?: PiSessionOptions["taskPermissions"]; taskWorkspace?: PiSessionOptions["taskWorkspace"] }, prompt: string): Promise<void> {
    if (!this.runtime) {
      await this.agents.start({ projectId: project.projectId, missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId, experimentId: input.experimentId, runId: null, jobId: null, taskId: input.taskId, agentId: input.agentId, role: input.role, cwd: input.cwd, packagePath: this.packagePath, ...(input.taskPermissions ? { taskPermissions: input.taskPermissions } : {}), ...(input.taskWorkspace ? { taskWorkspace: input.taskWorkspace } : {}) });
      try { await this.agents.prompt(input.agentId, prompt); } finally { this.agents.stop(input.agentId); }
      return;
    }
    const threadId = createId("thr"); const issuedAt = new Date().toISOString(); const key = `runtime:${input.taskId}`;
    await this.runtime.execute({ $schema: schemaUri("runtime-instruction"), schemaVersion: 1, instructionId: createId("ins"), projectId: project.projectId, idempotencyKey: `${key}:open`, proposedByAgentId: null, issuedAt, operation: "THREAD_OPEN", threadId, taskId: input.taskId, initialAgentId: input.agentId, ownerScope: { missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId, experimentId: input.experimentId, graphNodeId: null }, role: input.role, purpose: `Execute Autoresearch task ${input.taskId}`, executionMode: "background", parentThreadId: null, inputRefs: [], skillIds: [], capabilities: [], taskPermissions: input.taskPermissions ?? null, taskWorkspace: input.taskWorkspace ?? null, budget: { maximumToolCalls: 200, maximumModelTokens: 100_000, maximumWallClockSeconds: 7_200 } });
    try {
      await this.runtime.execute({ $schema: schemaUri("runtime-instruction"), schemaVersion: 1, instructionId: createId("ins"), projectId: project.projectId, idempotencyKey: `${key}:step`, proposedByAgentId: null, issuedAt, operation: "THREAD_STEP", threadId, objective: prompt, expectedEpisodeType: `episode_${input.role}`, inputRefs: [], skillIds: [] });
    } finally {
      await this.runtime.execute({ $schema: schemaUri("runtime-instruction"), schemaVersion: 1, instructionId: createId("ins"), projectId: project.projectId, idempotencyKey: `${key}:stop`, proposedByAgentId: null, issuedAt: new Date().toISOString(), operation: "STOP", threadId, programId: null, reason: "Task session reached its boundary" });
    }
  }
  private write(projectId: string, key: string, path: string, value: JsonValue): string { const content = `${canonicalJson(value)}\n`; const digest = sha256(content); const intent = this.research.beginExternalOperation(projectId, "filesystem.write", `filesystem-write:${key}`, { path: resolve(path), digest, content }); mkdirSync(resolve(path, ".."), { recursive: true }); if (!existsSync(path) || sha256(readFileSync(path, "utf8")) !== digest) { const temporary = `${path}.${intent.intentId}.tmp`; writeFileSync(temporary, content, "utf8"); renameSync(temporary, path); } if (sha256(readFileSync(path, "utf8")) !== digest) throw new Error("Durable file write verification failed"); this.research.completeExternalOperation(projectId, intent.intentId, { path: resolve(path), digest }); return path; }
  private artifact(project: RegisteredProject, execution: AutoresearchProjection, experimentId: string | null, kind: string, mediaType: string, sourcePath: string, retentionClass: Artifact["retentionClass"] = "accepted_evidence"): Artifact { const artifactId = `art_${sha256({ autoresearchId: execution.autoresearchId, experimentId, kind, sourcePath: resolve(sourcePath) }).slice(7, 39)}`; const intent = this.research.beginExternalOperation(project.projectId, "artifact.copy", `artifact-copy:${artifactId}`, { artifactId, sourcePath: resolve(sourcePath), kind, mediaType, retentionClass }); const store = new ArtifactStore(join(project.repositoryRoot, ".nosh", "artifacts")); const artifact = store.add({ artifactId, projectId: project.projectId, kind, mediaType, sourcePath, retentionClass }); store.resolve(artifact.artifactId, artifact.version); this.research.completeExternalOperation(project.projectId, intent.intentId, { artifactId: artifact.artifactId, contentHash: artifact.contentHash, version: artifact.version }); const record: JsonValue = { $schema: schemaUri("artifact"), schemaVersion: 1, artifactId: artifact.artifactId, projectId: project.projectId, kind, mediaType, contentHash: artifact.contentHash, sizeBytes: artifact.sizeBytes, version: artifact.version, producer: { type: "noshd" }, scope: { missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId, experimentId }, git: null, evaluationContractHash: execution.evaluationContractHash, retentionClass, remotePreviewPolicy: "encrypted_allowed", redactionStatus: "checked", createdAt: artifact.createdAt }; this.submit(project, execution, `artifact:${artifact.artifactId}`, record, `artifact-record:${artifact.artifactId}`, null, experimentId); return artifact; }
}

type TaskPacket = { $schema: string; schemaVersion: number; templateVersion: string; taskId: string; attempt: number; taskType: string; assignedRole: "general_worker"; assignedAgentId: string; scope: { projectId: string; missionId: string | null; directionId: string | null; autoresearchId: string; experimentId: string; graphNodeId: string }; goalStack: { projectGoalId: string; projectGoalSummary: string; missionCriterionIds: string[]; missionCriterionSummary: string; directionQuestionId: string | null; directionQuestionSummary: string | null; nodeObjective: string }; whyNow: string; instructions: string[]; inScope: string[]; outOfScope: string[]; inputArtifactIds: string[]; inputEvidenceIds: string[]; requiredOutputs: Array<{ outputId: string; kind: string; required: boolean }>; acceptanceCriteria: Array<{ criterionId: string; statement: string; validatorIds: string[]; reviewRubricIds: string[]; required: boolean }>; workspace: { worktreeId: string; branch: string; startingCommit: string; writeScopes: string[]; protectedScopes: string[] }; permissions: TaskPermissions; budget: { deadline: string; maximumWallClockSeconds: number; maximumModelTokens: number; maximumToolCalls: number; maximumRepairAttempts: number }; progressPolicy: { milestoneIntervalSeconds: number; emitOnFirstDurableDelta: boolean; emitOnBlocker: boolean; emitOnAnomaly: boolean; maximumSilentSeconds: number }; responseSchema: string; observedVersions: Record<string, number>; lease: { leaseId: string; expiresAt: string; heartbeatSeconds: number }; issuedBy: "research_director"; issuedAt: string };
function parseContract(value: JsonValue): Contract {
  const contract = value as unknown as Partial<Contract>;
  const metric = contract.primaryMetric;
  const execution = contract.execution;
  const stops = contract.stopConditions;
  if (!metric || !metric.name || !["maximize", "minimize"].includes(metric.objective) || !Number.isFinite(metric.minimumEffect) || !execution || !["native", "wsl2"].includes(execution.runner) || !Array.isArray(execution.command) || !execution.command.length || !execution.resultPath || !Number.isInteger(execution.timeoutSeconds) || execution.timeoutSeconds <= 0 || stops?.target !== undefined && !Number.isFinite(stops.target) || stops?.maximumNoProgressRounds !== undefined && (!Number.isInteger(stops.maximumNoProgressRounds) || stops.maximumNoProgressRounds < 1)) throw new Error("Autoresearch evaluation contract lacks a runnable primary metric, execution command, or valid stop condition");
  return { ...contract, primaryMetric: metric, baselineMetrics: contract.baselineMetrics ?? {}, stopConditions: stops, execution } as Contract;
}
function managerFor(project: RegisteredProject): GitWorkspaceManager { return new GitWorkspaceManager(project.repositoryRoot, join(project.repositoryRoot, ".nosh", "worktrees"), join(project.repositoryRoot, ".nosh", "git")); }
function branchName(autoresearchId: string, experimentId: string): string { return `ar/${autoresearchId.slice(3, 11)}/${experimentId.slice(4, 12)}`; }
function roundWidths(execution: AutoresearchProjection, contract: Contract): number[] { const configured = contract.roundWidths?.filter((value) => Number.isInteger(value) && value > 0) ?? []; return configured.length ? configured : execution.maximumExperiments >= 3 ? [2, ...Array(execution.maximumExperiments - 2).fill(1)] : Array(execution.maximumExperiments).fill(1); }
function roundAt(ordinal: number, widths: number[]): number { let total = 0; for (let index = 0; index < widths.length; index += 1) { total += widths[index]!; if (ordinal <= total) return index + 1; } return widths.length; }
function roundBoundary(count: number, widths: number[]): boolean { let total = 0; return widths.some((width) => (total += width) === count); }
function noProgressRounds(records: Record<string, unknown>[]): number {
  let count = 0;
  for (const record of [...records].reverse()) {
    if (record.$schema !== schemaUri("autoresearch-round")) continue;
    if (Array.isArray(record.promotedExperimentIds) && record.promotedExperimentIds.length) break;
    count += 1;
  }
  return count;
}
function uniqueResults(records: Record<string, unknown>[]): ExperimentResult[] { const map = new Map<string, ExperimentResult>(); for (const record of records) if (record.$schema === schemaUri("experiment-result")) map.set((record as { experimentId: string }).experimentId, record as unknown as ExperimentResult); return [...map.values()]; }
function isMetricObject(value: JsonValue): value is Record<string, JsonValue> { return Boolean(value && !Array.isArray(value) && typeof value === "object"); }
function primaryMetric(metrics: JsonValue, name: string): { value: number | null; failure: string | null } {
  if (!isMetricObject(metrics)) return { value: null, failure: `Metric ${name} is missing or non-finite` };
  const value = metrics[name];
  return typeof value === "number" && Number.isFinite(value) ? { value, failure: null } : { value: null, failure: `Metric ${name} is missing or non-finite` };
}
function metricValue(metrics: JsonValue, name: string): number { const primary = primaryMetric(metrics, name); if (primary.value === null) throw new Error(primary.failure!); return primary.value; }
function score(result: ExperimentResult): number { return result.comparison.improvement ?? Number.NEGATIVE_INFINITY; }
function same(left: string[] | undefined, right: string[]): boolean { return Boolean(left && left.length === right.length && left.every((value, index) => value === right[index])); }
function git(cwd: string, args: string[]): string { const result = spawnSync("git", ["-C", cwd, ...args], { encoding: "utf8", windowsHide: true }); if (result.status !== 0) throw new Error(result.stderr.trim() || `git ${args[0]} failed`); return result.stdout.trim(); }
function postflight(worktree: string, packet: TaskPacket, record: JsonValue): string[] { const parsed = validateRecord(schemaUri("general-worker-completion"), record); if (!parsed.ok) return parsed.errors.map((error) => `${error.pointer} ${error.message}`); const value = parsed.value as unknown as { taskOutcome: string; readyForReview: boolean; readyForDeterministicPostflight: boolean; codeChanges: { startingCommit: string; endingCommit: string; changedPaths: string[]; branch: string }; commands: Array<{ exitCode: number | null }>; criteria: Array<{ criterionId: string; workerClaim: string; validatorRunIds: string[] }> }; const issues: string[] = []; if (value.taskOutcome !== "completed" || !value.readyForReview || !value.readyForDeterministicPostflight) issues.push("completion is not postflight-ready"); issues.push(...validateGitCompletion(worktree, packet.workspace, value.codeChanges)); if (value.commands.some((command) => command.exitCode !== 0)) issues.push("a declared validator failed"); for (const criterion of packet.acceptanceCriteria) if (!value.criteria.some((entry) => entry.criterionId === criterion.criterionId && entry.workerClaim === "satisfied" && entry.validatorRunIds.length)) issues.push(`criterion ${criterion.criterionId} lacks a passing validator`); return [...new Set(issues)]; }
function reviewPasses(review: ReviewVerdict, request: ReviewRequest, reviewerId: string): boolean { if (!validateRecord(schemaUri("review-verdict"), review as unknown as JsonValue).ok || review.reviewId !== request.reviewId || review.reviewRequestId !== request.reviewRequestId || review.reviewType !== request.reviewType || review.reviewerAgentId !== reviewerId || review.independenceCheck !== "pass" || review.verdict !== "PASS" || review.target?.targetType !== request.target.targetType || review.target.targetId !== request.target.targetId || review.target.targetVersion !== request.target.targetVersion) return false; if (!request.criteria.every((criterion) => review.criteria?.some((entry) => entry.criterionId === criterion.criterionId && entry.status === "PASS"))) return false; return request.requiredArtifactIds.every((id) => review.reviewedArtifactIds?.includes(id)) && request.requiredEvidenceIds.every((id) => review.reviewedEvidenceIds?.includes(id)); }
function event(execution: AutoresearchProjection, type: string, payload: JsonValue): EventDraft { return { $schema: schemaUri("event"), schemaVersion: 1, retention: "persistent", type, source: "autoresearch_supervisor", scope: { projectId: execution.projectId, missionId: execution.missionId, directionId: execution.directionId, autoresearchId: execution.autoresearchId, experimentId: null, runId: null, jobId: null, agentId: null }, correlationId: execution.autoresearchId, causationId: null, payload }; }
