import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { createId } from "@nosh/core";
import { ArtifactStore } from "@nosh/evidence";
import { EventStore, type RegisteredProject } from "@nosh/persistence";
import type { AgentInspection, PiAdapter, PiSessionOptions } from "@nosh/pi-adapter";
import { schemaUri, type EventDraft, type JsonValue } from "@nosh/wire";
import { describe, expect, it } from "vitest";
import { DirectionSupervisor } from "./direction-supervisor.js";
import { MissionSupervisor } from "./mission-supervisor.js";
import { ResearchControl } from "./research-control.js";

class FixtureAgents {
  private readonly sessions = new Map<string, PiSessionOptions>();
  constructor(private readonly append: (draft: EventDraft) => void, private readonly failGeneralWorkers = false) {}
  inspect(): AgentInspection[] { return [...this.sessions.values()].map((session) => ({ ...session, piSessionId: `pi_${session.agentId}`, status: "running", currentTool: null, startedAt: new Date().toISOString(), lastEventAt: new Date().toISOString(), modelProvider: session.model?.provider ?? null, modelId: session.model?.id ?? null, modelName: null, thinkingLevel: session.thinkingLevel ?? "medium", contextTokens: null, contextWindow: null, contextPercent: null })); }
  async start(options: PiSessionOptions): Promise<AgentInspection> { this.sessions.set(options.agentId, options); return this.inspect().find((agent) => agent.agentId === options.agentId)!; }
  async prompt(agentId: string, prompt: string): Promise<void> {
    const session = this.sessions.get(agentId)!; const taskId = session.taskId; if (!taskId) throw new Error("Fixture session requires a Task ID"); const target = /target\.targetId=([a-z0-9_]+)/.exec(prompt)?.[1] ?? ""; const packetText = prompt.split("before work: ")[1]?.split(". Then complete")[0]; const packet = packetText ? JSON.parse(packetText) as { attempt: number; workspace: { startingCommit: string; branch: string }; lease: { leaseId: string }; requiredOutputs: Array<{ outputId: string }>; acceptanceCriteria: Array<{ criterionId: string }> } : null; const reviewRequestText = prompt.split("Review Request: ")[1]?.split(". Submit")[0]; const reviewRequest = reviewRequestText ? JSON.parse(reviewRequestText) as { reviewId: string; reviewRequestId: string; reviewType: string; target: { targetType: string; targetId: string; targetVersion: number }; criteria: Array<{ criterionId: string; required: boolean }>; requiredArtifactIds: string[]; requiredEvidenceIds: string[] } : null; const now = new Date().toISOString();
    if (packet) this.submit(session, { $schema: schemaUri("task-acknowledgement"), schemaVersion: 1, taskId, attempt: packet.attempt, agentId, decision: "accepted", understoodObjective: "Complete the bounded node", understoodOutputIds: packet.requiredOutputs.map((output) => output.outputId), understoodCriterionIds: packet.acceptanceCriteria.map((criterion) => criterion.criterionId), observedLeaseId: packet.lease.leaseId, observedStartingCommit: packet.workspace.startingCommit, conflicts: [], clarificationRequest: null, submittedAt: now });
    let record: JsonValue;
    if (session.role === "mission_director") record = { $schema: schemaUri("mission-director-cycle"), directorAgentId: agentId, missionId: session.missionId, observedGraphVersion: Number(/graph version (\d+)/.exec(prompt)?.[1]), northStarCheck: { currentWorkContributes: true } };
    else if (session.role === "research_director") record = { $schema: schemaUri("research-director-cycle"), directorAgentId: agentId, directionId: session.directionId, observedGraphVersion: Number(/graph version (\d+)/.exec(prompt)?.[1]), evaluationContractHash: /sha256:[0-9a-f]{64}/.exec(prompt)?.[0] ?? "", questionCheck: { currentWorkContributes: true } };
    else if (session.role === "reviewer") { const reviewId = reviewRequest?.reviewId ?? createId("rev"); record = { $schema: schemaUri("review-verdict"), schemaVersion: 1, templateVersion: "1.0.0", reviewId, reviewRequestId: reviewRequest?.reviewRequestId ?? `request_${reviewId.slice(4)}`, reviewType: reviewRequest?.reviewType ?? (target.startsWith("mis_") ? "mission_completion" : target.startsWith("dir_") ? "direction_closure" : "task"), target: reviewRequest?.target ?? { targetType: "graph_node", targetId: target, targetVersion: 1 }, reviewerAgentId: agentId, independenceCheck: "pass", verdict: "PASS", summary: "Fixture review passed", criteria: reviewRequest?.criteria.map((criterion) => ({ criterionId: criterion.criterionId, required: criterion.required, status: "PASS", finding: "All fixture inputs passed", evidenceRefs: [], confidence: "high", defectIds: [] })) ?? [{ criterionId: "criterion_fixture", status: "PASS", finding: "All fixture inputs passed", evidenceRefs: [], confidence: "high", defectIds: [] }], defects: [], missingRequiredInputs: [], scientificIntegrityFlags: [], recommendedGraphAction: "accept_node", recommendedPromotion: "not_applicable", reviewedArtifactIds: reviewRequest?.requiredArtifactIds ?? [], reviewedEvidenceIds: reviewRequest?.requiredEvidenceIds ?? [], submittedAt: now }; }
    else if (session.role === "librarian_researcher" && packet) { const artifacts = new ArtifactStore(join(session.cwd, ".nosh", "artifacts")); const sourcePath = join(session.cwd, `.fixture-source-${taskId}.txt`); const reportPath = join(session.cwd, `.fixture-report-${taskId}.md`); const bibliographyPath = join(session.cwd, `.fixture-bibliography-${taskId}.bib`); writeFileSync(sourcePath, "Primary fixture source\n"); writeFileSync(reportPath, "# Fixture report\n"); writeFileSync(bibliographyPath, "@misc{fixture}\n"); const sourceArtifact = artifacts.add({ artifactId: createId("art"), projectId: session.projectId, kind: "source", mediaType: "text/plain", sourcePath, retentionClass: "accepted_evidence" }); const reportArtifact = artifacts.add({ artifactId: createId("art"), projectId: session.projectId, kind: "report", mediaType: "text/markdown", sourcePath: reportPath, retentionClass: "accepted_evidence" }); const bibliographyArtifact = artifacts.add({ artifactId: createId("art"), projectId: session.projectId, kind: "bibliography", mediaType: "application/x-bibtex", sourcePath: bibliographyPath, retentionClass: "accepted_evidence" }); record = { $schema: schemaUri("librarian-completion"), schemaVersion: 1, taskOutcome: "completed", researchQuestion: "Fixture literature question", searchCoverage: { databases: ["fixture"], queries: ["fixture query"], dateRange: { from: null, to: null }, language: ["en"], inclusionCriteria: ["primary"], exclusionCriteria: ["none"] }, sources: [{ sourceId: `source_${taskId.slice(4)}`, sourceType: "primary_source", title: "Fixture source", authors: ["Fixture Author"], publicationDate: null, canonicalUrl: "https://example.com/fixture", persistentId: null, version: "1", primarySource: true, accessedAt: now, artifactId: sourceArtifact.artifactId, relevance: "Direct fixture support" }], findings: [{ findingId: `finding_${taskId.slice(4)}`, statement: "Fixture finding", support: [{ sourceId: `source_${taskId.slice(4)}`, locator: "line 1", artifactId: sourceArtifact.artifactId }], confidence: "high", noveltyImplication: "Fixture only" }], contradictions: [], evaluationDifferences: [], knowledgeGaps: [], candidateClaimEffects: [], bibliographyArtifactId: bibliographyArtifact.artifactId, reportArtifactId: reportArtifact.artifactId, readyForReview: true }; }
    else if (session.role === "general_worker" && packet) { let endingCommit = packet.workspace.startingCommit; const changedPaths: string[] = []; if (!this.failGeneralWorkers) { const name = `fixture-${taskId}.txt`; writeFileSync(join(session.cwd, name), "Reviewed fixture output\n"); git(session.cwd, ["add", "--", name]); git(session.cwd, ["commit", "-m", `fixture ${taskId}`]); endingCommit = git(session.cwd, ["rev-parse", "HEAD"]); changedPaths.push(name); } record = { $schema: schemaUri("general-worker-completion"), schemaVersion: 1, taskOutcome: this.failGeneralWorkers ? "failed" : "completed", workPerformed: [{ action: "action_implementation", subject: "Fixture output", artifactIds: [] }], codeChanges: { startingCommit: packet.workspace.startingCommit, endingCommit, changedPaths, diffArtifactId: null, branch: packet.workspace.branch }, commands: [{ commandId: `validator_${taskId.slice(4)}`, displayCommand: "fixture validator", exitCode: this.failGeneralWorkers ? 1 : 0, resultArtifactId: null }], criteria: [{ criterionId: packet.acceptanceCriteria[0]!.criterionId, workerClaim: this.failGeneralWorkers ? "unsatisfied" : "satisfied", validatorRunIds: [`validator_${taskId.slice(4)}`], artifactIds: [], notes: "Fixture validator" }], scientificImpact: { claimIds: [], evidenceIds: [], interpretation: "Fixture impact" }, deviations: [], newRisks: [], unresolvedItems: [], suggestedNextActions: [], readyForDeterministicPostflight: !this.failGeneralWorkers, readyForReview: !this.failGeneralWorkers };
    } else if (session.role === "librarian_researcher") record = { $schema: schemaUri("librarian-completion"), taskOutcome: "completed", readyForReview: true }; else record = { $schema: schemaUri("general-worker-completion"), taskOutcome: "completed", readyForReview: true, readyForDeterministicPostflight: true, codeChanges: { endingCommit: git(session.cwd, ["rev-parse", "HEAD"]) } };
    this.submit(session, record);
    if (session.directionId && ["general_worker", "librarian_researcher"].includes(session.role)) this.submit(session, { $schema: schemaUri("evidence"), evidenceId: createId("evd"), statement: "Fixture result", sourceRefs: [{ refType: "task", refId: session.taskId, locator: "fixture" }] });
  }
  stop(agentId: string): void { this.sessions.delete(agentId); }
  private submit(session: PiSessionOptions, record: JsonValue): void { const scope = { projectId: session.projectId, missionId: session.missionId, directionId: session.directionId, autoresearchId: null, experimentId: null, runId: null, jobId: null, agentId: session.agentId }; this.append({ $schema: schemaUri("event"), schemaVersion: 1, retention: "persistent", type: "record.submitted", source: "fixture", scope, correlationId: `task:${session.taskId}`, causationId: null, payload: record }); }
}

describe("MissionSupervisor", () => {
  it("runs typed Director, worker, independent Review, and final Review gates", async () => {
    const directory = mkdtempSync(join(tmpdir(), "nosh-supervisor-")); const repositoryRoot = join(directory, "repository"); mkdirSync(repositoryRoot); initializeRepository(repositoryRoot); const projectId = createId("prj"); const project: RegisteredProject = { projectId, repositoryRoot, databasePath: join(directory, "project.sqlite"), registeredAt: new Date().toISOString() }; const store = new EventStore(project.databasePath); const publish = () => undefined; const research = new ResearchControl(() => store, () => project, publish); const fixture = new FixtureAgents((draft) => { store.append(draft); }); const supervisor = new MissionSupervisor(research, fixture as unknown as PiAdapter, () => [project], join(directory, "pi-package"), (draft) => { store.append(draft); });
    try {
      let mission = research.createMission(projectId, { title: "Fixture", objective: "Produce a reviewed result", deliverables: ["Reviewed result"], successCriteria: ["All nodes accepted"], idempotencyKey: "fixture-create" }); for (const next of ["planning", "awaiting_approval", "running"] as const) mission = research.transitionMission(projectId, mission.entityId, mission.version, next, `fixture-${next}`);
      for (let cycle = 0; cycle < 10 && research.mission(projectId, mission.entityId).state !== "completed"; cycle += 1) { await supervisor.tick(); await new Promise((resolve) => setTimeout(resolve, 20)); }
      const completed = research.mission(projectId, mission.entityId); const failures = research.scopedEvents(projectId, mission.entityId).filter((entry) => ["task.execution_failed", "task.postflight_failed", "mission.supervisor_error", "mission.completion_rejected", "focus.alarm"].includes(entry.type)); expect({ state: completed.state, failures }).toEqual({ state: "completed", failures: [] }); expect(completed.value.nodes.every((node) => node.state === "accepted")).toBe(true); expect(research.records(projectId, "mission-director-cycle").length).toBeGreaterThanOrEqual(3); expect(research.records(projectId, "task-packet").length).toBeGreaterThanOrEqual(3); expect(research.records(projectId, "task-acknowledgement").length).toBeGreaterThanOrEqual(3); expect(research.records(projectId, "review-request").length).toBeGreaterThanOrEqual(4); expect(research.records(projectId, "review-verdict").length).toBeGreaterThanOrEqual(4); expect(research.submitted(projectId).some((entry) => entry.event.scope.missionId === mission.entityId && (entry.record as { $schema?: string }).$schema === schemaUri("mission-completion-packet"))).toBe(true); expect(store.operationIntents(projectId, "pending")).toEqual([]);
    } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
  });

  it("runs typed Direction Director, immutable baseline, Evidence, and closure Review gates", async () => {
    const directory = mkdtempSync(join(tmpdir(), "nosh-direction-supervisor-")); const repositoryRoot = join(directory, "repository"); mkdirSync(repositoryRoot); initializeRepository(repositoryRoot); const projectId = createId("prj"); const project: RegisteredProject = { projectId, repositoryRoot, databasePath: join(directory, "project.sqlite"), registeredAt: new Date().toISOString() }; const store = new EventStore(project.databasePath); const research = new ResearchControl(() => store, () => project, () => undefined); const fixture = new FixtureAgents((draft) => { store.append(draft); }); const supervisor = new DirectionSupervisor(research, fixture as unknown as PiAdapter, () => [project], join(directory, "pi-package"), (draft) => { store.append(draft); });
    try {
      let direction = research.createDirection(projectId, { question: "Does the bounded change improve the metric?", decisionUse: "Choose whether to adopt it", idempotencyKey: "direction-create" }); for (const next of ["proposed", "active"] as const) direction = research.transitionDirection(projectId, direction.entityId, direction.version, next, `direction-${next}`);
      for (let cycle = 0; cycle < 10 && research.direction(projectId, direction.entityId).state !== "closed"; cycle += 1) { await supervisor.tick(); await new Promise((resolve) => setTimeout(resolve, 20)); }
      const closed = research.direction(projectId, direction.entityId); expect(closed.state).toBe("closed"); expect(closed.value.acceptedBaseline?.commit).toMatch(/^[0-9a-f]{40}$/); expect(git(repositoryRoot, ["merge-base", "--is-ancestor", closed.value.acceptedBaseline!.commit, "HEAD"])).toBe(""); expect(closed.value.nodes.every((node) => node.state === "accepted")).toBe(true); expect(research.submitted(projectId).some((entry) => entry.event.scope.directionId === direction.entityId && (entry.record as { $schema?: string }).$schema === schemaUri("evidence"))).toBe(true); expect(research.records(projectId, "task-packet").some((record) => (record as { scope?: { directionId?: string } }).scope?.directionId === direction.entityId)).toBe(true); expect(research.records(projectId, "review-request").some((record) => (record as { scope?: { directionId?: string } }).scope?.directionId === direction.entityId)).toBe(true); expect(research.records(projectId, "research-director-cycle").length).toBeGreaterThanOrEqual(3); expect(research.submitted(projectId).some((entry) => entry.event.scope.directionId === direction.entityId && (entry.record as { $schema?: string }).$schema === schemaUri("direction-closure-packet"))).toBe(true); expect(store.operationIntents(projectId, "pending")).toEqual([]);
    } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
  });

  it("reconstructs Focus fingerprints when the supervisor process state is replaced", async () => {
    const directory = mkdtempSync(join(tmpdir(), "nosh-focus-recovery-")); const repositoryRoot = join(directory, "repository"); mkdirSync(repositoryRoot); initializeRepository(repositoryRoot); const projectId = createId("prj"); const project: RegisteredProject = { projectId, repositoryRoot, databasePath: join(directory, "project.sqlite"), registeredAt: new Date().toISOString() }; const store = new EventStore(project.databasePath); const research = new ResearchControl(() => store, () => project, () => undefined); const fixture = new FixtureAgents((draft) => { store.append(draft); }, true);
    try { let mission = research.createMission(projectId, { title: "Focus", objective: "Reject tunnel vision", deliverables: ["Reviewed result"], successCriteria: ["Repeated work is stopped"], idempotencyKey: "focus-create" }); for (const next of ["planning", "awaiting_approval", "running"] as const) mission = research.transitionMission(projectId, mission.entityId, mission.version, next, `focus-${next}`); for (let cycle = 0; cycle < 6 && !research.scopedEvents(projectId, mission.entityId, "focus.alarm").length; cycle += 1) { const supervisor = new MissionSupervisor(research, fixture as unknown as PiAdapter, () => [project], join(directory, "pi-package"), (draft) => { store.append(draft); }); await supervisor.tick(); await new Promise((resolve) => setTimeout(resolve, 20)); } expect(research.scopedEvents(projectId, mission.entityId, "focus.attempt_recorded").length).toBeGreaterThanOrEqual(2); expect(research.scopedEvents(projectId, mission.entityId, "focus.alarm")[0]?.payload).toMatchObject({ reasons: ["repeated_attempt_fingerprint"] }); expect(research.mission(projectId, mission.entityId).value.nodes.some((node) => node.state === "blocked")).toBe(true); } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
  });

  it("reconciles persisted Pi token use against the Mission ceiling", () => {
    const directory = mkdtempSync(join(tmpdir(), "nosh-budget-")); const repositoryRoot = join(directory, "repository"); mkdirSync(repositoryRoot); const projectId = createId("prj"); const project: RegisteredProject = { projectId, repositoryRoot, databasePath: join(directory, "project.sqlite"), registeredAt: new Date().toISOString() }; const store = new EventStore(project.databasePath); const research = new ResearchControl(() => store, () => project, () => undefined);
    try { const mission = research.createMission(projectId, { title: "Budget", objective: "Honor the ceiling", deliverables: ["Bounded result"], successCriteria: ["No overrun"], idempotencyKey: "budget-create" }); const scope = { projectId, missionId: mission.entityId, directionId: null, autoresearchId: null, experimentId: null, runId: null, jobId: null, agentId: createId("agt") }; store.append({ $schema: schemaUri("event"), schemaVersion: 1, retention: "persistent", type: "agent.completed", source: "pi", scope, correlationId: null, causationId: null, payload: { modelTokens: mission.value.budgets.maximumModelTokens + 1 } }); store.append({ $schema: schemaUri("event"), schemaVersion: 1, retention: "persistent", type: "job.state_changed", source: "jobs", scope: { ...scope, jobId: createId("job") }, correlationId: null, causationId: null, payload: { usesGpu: true, startedAt: "2026-07-18T00:00:00.000Z", finishedAt: "2026-07-18T00:00:07.000Z" } }); const use = research.missionBudgetUse(projectId, mission.entityId); expect(use.modelTokens).toBe(mission.value.budgets.maximumModelTokens + 1); expect(use.gpuSeconds).toBe(7); expect(research.missionCompletionIssues(projectId, mission.entityId)).toContain("Mission model-token budget is exceeded"); } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
  });

  it("releases an orphaned working lease after supervisor restart", async () => {
    const directory = mkdtempSync(join(tmpdir(), "nosh-lease-recovery-")); const repositoryRoot = join(directory, "repository"); mkdirSync(repositoryRoot); initializeRepository(repositoryRoot); const projectId = createId("prj"); const project: RegisteredProject = { projectId, repositoryRoot, databasePath: join(directory, "project.sqlite"), registeredAt: new Date().toISOString() }; const store = new EventStore(project.databasePath); const research = new ResearchControl(() => store, () => project, () => undefined); const fixture = new FixtureAgents((draft) => { store.append(draft); });
    try { let mission = research.createMission(projectId, { title: "Lease recovery", objective: "Resume without a lost owner", deliverables: ["Recovered result"], successCriteria: ["Every node is accepted"], idempotencyKey: "lease-create" }); for (const next of ["planning", "awaiting_approval", "running"] as const) mission = research.transitionMission(projectId, mission.entityId, mission.version, next, `lease-${next}`); const node = mission.value.nodes[0]!; const leaseId = createId("tsk"); mission = research.transitionMissionNode(projectId, mission.entityId, mission.version, node.id, "leased", "orphan-lease", { leaseId, ownerId: createId("agt"), version: mission.version, expiresAt: new Date(Date.now() + 60_000).toISOString() }); research.transitionMissionNode(projectId, mission.entityId, mission.version, node.id, "working", "orphan-working"); for (let cycle = 0; cycle < 10 && research.mission(projectId, mission.entityId).state !== "completed"; cycle += 1) { const supervisor = new MissionSupervisor(research, fixture as unknown as PiAdapter, () => [project], join(directory, "pi-package"), (draft) => { store.append(draft); }); await supervisor.tick(); await new Promise((resolve) => setTimeout(resolve, 20)); } expect(research.mission(projectId, mission.entityId).state).toBe("completed"); expect(research.scopedEvents(projectId, mission.entityId, "mission.node_recovered")[0]?.payload).toMatchObject({ nodeId: node.id, priorState: "working", disposition: "ready_for_new_lease" }); } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
  });
});

function initializeRepository(path: string): void { git(path, ["init", "-b", "main"]); git(path, ["config", "user.email", "fixture@nosh.test"]); git(path, ["config", "user.name", "NOSH Fixture"]); writeFileSync(join(path, ".gitignore"), ".nosh/\n.fixture-*\n"); writeFileSync(join(path, "README.md"), "# Fixture\n"); git(path, ["add", "--", ".gitignore", "README.md"]); git(path, ["commit", "-m", "fixture baseline"]); }
function git(path: string, args: string[]): string { const result = spawnSync("git", ["-C", path, ...args], { encoding: "utf8", windowsHide: true }); if (result.status !== 0) throw new Error(result.stderr.trim() || `git ${args[0]} failed`); return result.stdout.trim(); }
