import sodium from "libsodium-wrappers-sumo";
import { createId } from "@nosh/core";
import { describe, expect, it } from "vitest";
import { DeviceRegistry, RemoteCommandValidator, createDeviceKeys, decryptVault, encryptCommand, encryptVault, openRelayPayload, sealRelayPayload, unlockWrappedAccountKey } from "./index.js";

describe("remote cryptographic boundary", () => {
  it("pairs, wraps keys, signs, encrypts, rejects replay effects, and revokes", async () => {
    await sodium.ready; const keys = await createDeviceKeys(); const registry = new DeviceRegistry(); const pairing = await registry.createPairing(); registry.present(pairing.capability, { deviceId: keys.deviceId, signingPublicKey: keys.signingPublicKey, agreementPublicKey: keys.agreementPublicKey });
    const accountKey = sodium.randombytes_buf(32); const approved = registry.approve(pairing.capability, pairing.verificationCode, ["mission.pause"], accountKey); expect(await unlockWrappedAccountKey(approved.wrappedAccountKey, keys)).toEqual(accountKey);
    const accountId = "acc_0123456789abcdef"; const command = await encryptCommand({ protocolVersion: 1, accountId, commandId: createId("cmd"), idempotencyKey: "idempotency-remote-0001", deviceId: keys.deviceId, projectId: createId("prj"), targetType: "mission", targetId: createId("mis"), expectedVersion: 4, type: "mission.pause", requiredPermission: "mission.pause", keyVersion: 1, issuedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString() }, { mode: "safe" }, accountKey, keys.signingSecretKey);
    const validator = new RemoteCommandValidator(registry, accountKey, accountId, () => 4); expect(await validator.validate(command)).toEqual({ replayed: false, payload: { mode: "safe" } }); expect((await validator.validate(command)).replayed).toBe(true); const { nonce: _, ciphertext: __, signature: ___, ...header } = command; const conflicting = await encryptCommand(header, { mode: "immediate" }, accountKey, keys.signingSecretKey); await expect(validator.validate(conflicting)).rejects.toThrow("different command"); registry.revoke(keys.deviceId); command.idempotencyKey = "idempotency-remote-0002"; await expect(validator.validate(command)).rejects.toThrow("revoked");
    const stale = new RemoteCommandValidator(new DeviceRegistry({ capabilities: [], devices: [{ ...approved.device, revokedAt: null }] }), accountKey, accountId, () => 4, () => false, 2); await expect(stale.validate({ ...command, idempotencyKey: "idempotency-remote-0003" })).rejects.toThrow("key version is stale");
  });
  it("keeps command metadata opaque to the relay", async () => { await sodium.ready; const key = sodium.randombytes_buf(32); const ciphertext = await sealRelayPayload({ type: "mission.pause", project: "secret" }, key); expect(ciphertext).not.toContain("mission"); expect(await openRelayPayload(ciphertext, key)).toEqual({ type: "mission.pause", project: "secret" }); });
  it("binds foreground messages to an explicitly permitted thread", async () => { await sodium.ready; const keys = await createDeviceKeys(); const registry = new DeviceRegistry(); const pairing = await registry.createPairing(); registry.present(pairing.capability, { deviceId: keys.deviceId, signingPublicKey: keys.signingPublicKey, agreementPublicKey: keys.agreementPublicKey }); const accountKey = sodium.randombytes_buf(32); registry.approve(pairing.capability, pairing.verificationCode, ["thread.message"], accountKey); const accountId = "acc_0123456789abcdef"; const header = { protocolVersion: 1 as const, accountId, commandId: createId("cmd"), idempotencyKey: "idempotency-thread-0001", deviceId: keys.deviceId, projectId: createId("prj"), targetType: "thread" as const, targetId: createId("thr"), expectedVersion: 2, type: "thread.message" as const, requiredPermission: "thread.message", keyVersion: 1, issuedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString() }; const validator = new RemoteCommandValidator(registry, accountKey, accountId, () => 2); expect(await validator.validate(await encryptCommand(header, { message: "continue" }, accountKey, keys.signingSecretKey))).toEqual({ replayed: false, payload: { message: "continue" } }); await expect(validator.validate(await encryptCommand({ ...header, commandId: createId("cmd"), idempotencyKey: "idempotency-thread-0002", targetType: "mission" }, { message: "continue" }, accountKey, keys.signingSecretKey))).rejects.toThrow("capability"); });
  it("unlocks a password vault locally with Argon2id", async () => { const vault = await encryptVault({ secret: "local" }, "correct horse battery staple"); expect(await decryptVault(vault, "correct horse battery staple")).toEqual({ secret: "local" }); await expect(decryptVault(vault, "wrong")).rejects.toThrow(); });
});
