import type { DeviceKeys, Vault } from "@nosh/crypto";
import type { JsonValue, RemoteCommandEnvelope, RemoteCommandType } from "@nosh/wire";
import type { Agent, AutoresearchRecord, DirectionRecord, Job, MissionRecord, NoshEvent, Project, Stored, ThreadRecord } from "./api.js";
import { cacheEncrypted, readEncrypted } from "./cache.js";

export type RemoteFrame = { sequence?: number; frameId: string; deviceId: string; kind: "event" | "snapshot" | "command" | "ack"; ciphertext?: string };
export type PairedVault = DeviceKeys & { accountId: string; accountKey: string; keyVersion?: number };
type Snapshot = { type: "nosh.snapshot.v1"; generatedAt: string; projects: Project[]; missions: Record<string, Array<Stored<MissionRecord>>>; directions: Record<string, Array<Stored<DirectionRecord>>>; autoresearch: Record<string, Array<Stored<AutoresearchRecord>>>; threads?: Record<string, Array<Stored<ThreadRecord>>>; records: Record<string, unknown[]>; papers: Record<string, { markdown: string; bibliography: string }>; events: Record<string, NoshEvent[]>; agents: Agent[]; jobs: Job[] };
type Ack = { commandId?: string; accepted: boolean; replayed?: boolean; currentVersion?: number; error?: string };

export class RemoteConnection {
  private socket: WebSocket | undefined; private cursor: number; private stopped = false; private reconnect: number | undefined; private inbound = Promise.resolve();
  constructor(private readonly relayUrl: string, private readonly channelId: string, private readonly keys: DeviceKeys, private readonly receive: (frame: RemoteFrame) => void | Promise<void>) { this.cursor = Number(localStorage.getItem(`nosh.remote.cursor.${channelId}`) ?? "0"); }
  async connect(): Promise<void> { this.stopped = false; const modules = await import("@nosh/crypto"); const challengeResponse = await fetch(new URL(`/v1/channels/${this.channelId}/challenge`, this.relayUrl), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ deviceId: this.keys.deviceId }) }); if (!challengeResponse.ok) throw new Error("Relay authentication challenge failed"); const { challenge } = await challengeResponse.json() as { challenge: string }; const signature = await modules.signRelayChallenge(this.channelId, challenge, this.keys); const url = new URL(`/v1/channels/${this.channelId}`, this.relayUrl); url.protocol = url.protocol === "https:" ? "wss:" : "ws:"; url.searchParams.set("deviceId", this.keys.deviceId); url.searchParams.set("after", String(this.cursor)); url.searchParams.set("challenge", challenge); url.searchParams.set("signature", signature); const socket = new WebSocket(url); this.socket = socket; await new Promise<void>((resolve, reject) => { socket.onopen = () => resolve(); socket.onerror = () => reject(new Error("Relay WebSocket connection failed")); }); socket.onmessage = (message) => { const frame = JSON.parse(String(message.data)) as RemoteFrame; this.inbound = this.inbound.then(async () => { await this.receive(frame); if (frame.sequence && frame.sequence > this.cursor) { this.cursor = frame.sequence; localStorage.setItem(`nosh.remote.cursor.${this.channelId}`, String(this.cursor)); } }).catch(() => undefined); }; socket.onclose = () => { if (!this.stopped) this.reconnect = window.setTimeout(() => void this.connect().catch(() => undefined), 2_000); }; }
  send(kind: "command" | "ack", ciphertext: string): boolean { if (this.socket?.readyState !== WebSocket.OPEN) return false; this.socket.send(JSON.stringify({ frameId: `frm_${crypto.randomUUID().replaceAll("-", "")}`, deviceId: this.keys.deviceId, kind, ciphertext })); return true; }
  async sendCommand(command: RemoteCommandEnvelope, accountKey: Uint8Array): Promise<boolean> { const { sealRelayPayload } = await import("@nosh/crypto"); return this.send("command", await sealRelayPayload(command, accountKey)); }
  close(): void { this.stopped = true; if (this.reconnect) clearTimeout(this.reconnect); this.socket?.close(); }
}

class RemoteSession {
  private snapshot: Snapshot | null = null; private accountKey: Uint8Array; private readonly connection: RemoteConnection; private readonly pending = new Map<string, { resolve: (ack: Ack) => void; reject: (error: Error) => void; timer: number }>(); private readonly listeners = new Set<(event: NoshEvent) => void>();
  constructor(private readonly relayUrl: string, private readonly channelId: string, private readonly vault: PairedVault, private readonly persist: (vault: PairedVault) => void | Promise<void> = () => undefined) { this.accountKey = decode(vault.accountKey); this.connection = new RemoteConnection(relayUrl, channelId, vault, (frame) => this.receive(frame)); }
  async start(): Promise<void> { this.snapshot = await readEncrypted<Snapshot>("remote", this.vault.accountKey) ?? null; try { await this.connection.connect(); } catch (error) { if (!this.snapshot) throw error; } if (!this.snapshot) for (let attempt = 0; attempt < 50 && !this.snapshot; attempt += 1) await new Promise((resolve) => setTimeout(resolve, 100)); if (!this.snapshot) throw new Error("Connected, but no encrypted Project snapshot arrived"); }
  stop(): void { this.connection.close(); }
  subscribe(listener: (event: NoshEvent) => void): () => void { this.listeners.add(listener); return () => this.listeners.delete(listener); }
  async api<T>(path: string, init?: RequestInit): Promise<T> {
    const url = new URL(path, "https://nosh.invalid"); const projectId = url.searchParams.get("projectId") ?? ""; const method = init?.method ?? "GET";
    if (method === "GET") { const snapshot = this.requiredSnapshot(); if (url.pathname === "/projects") return { projects: snapshot.projects } as T; if (url.pathname === "/models") return { models: [...new Map(snapshot.agents.filter((agent) => agent.modelProvider && agent.modelId).map((agent) => [`${agent.modelProvider}/${agent.modelId}`, { provider: agent.modelProvider, id: agent.modelId, name: agent.modelName ?? agent.modelId }])).values()] } as T; if (url.pathname === "/events") return { events: snapshot.events[projectId] ?? [] } as T; if (url.pathname === "/missions") return { missions: snapshot.missions[projectId] ?? [] } as T; if (url.pathname === "/directions") return { directions: snapshot.directions[projectId] ?? [] } as T; if (url.pathname === "/autoresearch") return { executions: snapshot.autoresearch[projectId] ?? [] } as T; if (url.pathname === "/threads") return { threads: snapshot.threads?.[projectId] ?? [] } as T; if (url.pathname === "/records") { const schema = url.searchParams.get("schema"); return { records: (snapshot.records[projectId] ?? []).filter((record) => !schema || (record as { $schema?: string }).$schema === `https://nosh.dev/schemas/${schema}/v1`) } as T; } if (url.pathname === "/paper") return (snapshot.papers[projectId] ?? { markdown: "", bibliography: "" }) as T; if (url.pathname === "/agents") return { agents: snapshot.agents } as T; if (url.pathname === "/jobs") return { jobs: snapshot.jobs } as T; }
    const steering = /^\/missions\/([^/]+)\/steer$/.exec(url.pathname); if (method === "POST" && steering?.[1]) { const body = JSON.parse(String(init?.body ?? "{}")) as { projectId: string; expectedVersion: number; message: string }; await this.command(body.projectId, "mission", steering[1], body.expectedVersion, "mission.steer", { message: body.message }); return { accepted: true } as T; }
    const control = /^\/missions\/([^/]+)\/control$/.exec(url.pathname); if (method === "POST" && control?.[1]) { const body = JSON.parse(String(init?.body ?? "{}")) as { projectId: string; expectedVersion: number; action: "pause" | "resume" | "stop"; mode: "safe" | "checkpoint" | "immediate" }; const operation = body.action === "pause" ? "mission.pause" : body.action === "stop" ? "mission.stop" : "mission.resume"; const ack = await this.command(body.projectId, "mission", control[1], body.expectedVersion, operation, operation === "mission.resume" ? {} : { mode: body.mode }); const stored = this.requiredSnapshot().missions[body.projectId]?.find((item) => item.entityId === control[1]); if (stored) { stored.version = ack.currentVersion ?? stored.version; stored.state = body.action === "pause" ? "paused" : body.action === "stop" ? "stopped" : "running"; stored.value.state = stored.state; } return { mission: stored } as T; }
    const mission = /^\/missions\/([^/]+)\/transition$/.exec(url.pathname); if (method === "POST" && mission?.[1]) { const body = JSON.parse(String(init?.body ?? "{}")) as { projectId: string; expectedVersion: number; next: string }; const operation = body.next === "running" ? "mission.resume" : ["pausing", "paused"].includes(body.next) ? "mission.pause" : ["stopping", "stopped"].includes(body.next) ? "mission.stop" : null; if (!operation) throw new Error("This Mission transition requires local approval and is unavailable remotely"); const payload = operation === "mission.pause" ? { mode: "safe" } : operation === "mission.stop" ? { mode: "safe" } : {}; const ack = await this.command(body.projectId, "mission", mission[1], body.expectedVersion, operation, payload); const stored = this.requiredSnapshot().missions[body.projectId]?.find((item) => item.entityId === mission[1]); if (stored) { stored.version = ack.currentVersion ?? stored.version; stored.state = operation === "mission.pause" ? "paused" : operation === "mission.stop" ? "stopped" : "running"; stored.value.state = stored.state; } return { mission: stored } as T; }
    const message = /^\/threads\/([^/]+)\/messages$/.exec(url.pathname); if (method === "POST" && message?.[1]) { const body = JSON.parse(String(init?.body ?? "{}")) as { projectId: string; message: string }; const stored = this.thread(body.projectId, message[1]); const ack = await this.command(body.projectId, "thread", message[1], stored.version, "thread.message", { message: body.message }); stored.version = ack.currentVersion ?? stored.version; return { accepted: true } as T; }
    if (method === "POST" && url.pathname === "/runtime/instructions") { const body = JSON.parse(String(init?.body ?? "{}")) as { projectId?: string; operation?: string; threadId?: string; programId?: string | null }; if (!body.projectId || !body.threadId || body.operation !== "STOP" || body.programId) throw new Error("Only stopping a foreground fork is available remotely"); const stored = this.thread(body.projectId, body.threadId); const ack = await this.command(body.projectId, "thread", body.threadId, stored.version, "thread.stop", {}); stored.version = ack.currentVersion ?? stored.version; stored.state = "completed"; stored.value.state = "completed"; return { accepted: true } as T; }
    throw new Error("This operation is read-only or unavailable while using the remote snapshot");
  }
  private async command(projectId: string, targetType: RemoteCommandEnvelope["targetType"], targetId: string, expectedVersion: number, type: RemoteCommandType, payload: JsonValue): Promise<Ack> { const { encryptCommand } = await import("@nosh/crypto"); const commandId = `cmd_${crypto.randomUUID().replaceAll("-", "")}`; const command = await encryptCommand({ protocolVersion: 1, accountId: this.vault.accountId, commandId, idempotencyKey: `remote-${crypto.randomUUID()}`, deviceId: this.vault.deviceId, projectId, targetType, targetId, expectedVersion, type, requiredPermission: type, keyVersion: this.vault.keyVersion ?? 1, issuedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString() }, payload, this.accountKey, this.vault.signingSecretKey); const result = new Promise<Ack>((resolve, reject) => { const timer = window.setTimeout(() => { this.pending.delete(commandId); reject(new Error("No live noshd acknowledgement; command execution is unconfirmed")); }, type === "thread.message" ? 600_000 : 20_000); this.pending.set(commandId, { resolve, reject, timer }); }); if (!await this.connection.sendCommand(command, this.accountKey)) { const pending = this.pending.get(commandId); if (pending) { clearTimeout(pending.timer); this.pending.delete(commandId); pending.reject(new Error("Workstation is offline; command was not executed")); } } return result; }
  private async receive(frame: RemoteFrame): Promise<void> { if (!frame.ciphertext || !["snapshot", "event", "ack"].includes(frame.kind)) return; const { openRelayPayload, unlockWrappedAccountKey } = await import("@nosh/crypto"); const value = await openRelayPayload(frame.ciphertext, this.accountKey); const rotation = value as { type?: string; deviceId?: string; keyVersion?: number; wrappedAccountKey?: string }; if (rotation.type === "nosh.key-rotation.v1") { if (rotation.deviceId !== this.vault.deviceId || !rotation.keyVersion || !rotation.wrappedAccountKey) return; const next = await unlockWrappedAccountKey(rotation.wrappedAccountKey, this.vault); this.accountKey.fill(0); this.accountKey = next; this.vault.accountKey = encode(next); this.vault.keyVersion = rotation.keyVersion; await this.persist(this.vault); return; } if (frame.kind === "snapshot" && (value as { type?: string }).type === "nosh.snapshot.v1") { this.snapshot = value as unknown as Snapshot; await cacheEncrypted("remote", this.snapshot, this.vault.accountKey); window.dispatchEvent(new Event("nosh-remote-snapshot")); return; } if (frame.kind === "event") { const event = value as unknown as NoshEvent; const snapshot = this.requiredSnapshot(); const events = snapshot.events[event.scope.projectId] ?? []; snapshot.events[event.scope.projectId] = [...events.filter((item) => item.eventId !== event.eventId), event].slice(-200); const payload = event.payload as { entityId?: string; state?: string; version?: number }; if (event.scope.missionId && payload.state) { const mission = snapshot.missions[event.scope.projectId]?.find((item) => item.entityId === event.scope.missionId); if (mission) { mission.state = payload.state; mission.value.state = payload.state; mission.version = payload.version ?? mission.version; } } await cacheEncrypted("remote", snapshot, this.vault.accountKey); for (const listener of this.listeners) listener(event); return; } const ack = value as Ack; if (ack.commandId) { const pending = this.pending.get(ack.commandId); if (pending) { clearTimeout(pending.timer); this.pending.delete(ack.commandId); if (ack.accepted) pending.resolve(ack); else pending.reject(new Error(ack.error ?? "Remote command rejected")); } } }
  private requiredSnapshot(): Snapshot { if (!this.snapshot) throw new Error("No encrypted Project snapshot is available yet"); return this.snapshot; }
  private thread(projectId: string, threadId: string): Stored<ThreadRecord> { const thread = this.requiredSnapshot().threads?.[projectId]?.find((item) => item.entityId === threadId); if (!thread || thread.value.executionMode !== "foreground_fork") throw new Error("Foreground thread is unavailable in the encrypted snapshot"); return thread; }
}

let active: RemoteSession | null = null;
export function remoteActive(): boolean { return active !== null; }
export async function startRemoteSession(relayUrl: string, channelId: string, vault: PairedVault, persist?: (vault: PairedVault) => void | Promise<void>): Promise<void> { active?.stop(); const session = new RemoteSession(relayUrl, channelId, vault, persist); await session.start(); active = session; }
export function remoteApi<T>(path: string, init?: RequestInit): Promise<T> { if (!active) return Promise.reject(new Error("Remote vault is locked")); return active.api<T>(path, init); }
export function subscribeRemote(receive: (event: NoshEvent) => void): () => void { return active?.subscribe(receive) ?? (() => undefined); }

export async function presentPairing(relayUrl: string, channelId: string, input: { capability: string; deviceId: string; signingPublicKey: string; agreementPublicKey: string }): Promise<void> { const response = await fetch(new URL(`/v1/channels/${channelId}/pairings`, relayUrl), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); if (!response.ok) throw new Error("Pairing capability was rejected"); }
export async function finishPairing(relayUrl: string, channelId: string, capability: string, keys: DeviceKeys): Promise<{ accountId: string; accountKey: Uint8Array; keyVersion: number }> { const response = await fetch(new URL(`/v1/channels/${channelId}/pairings?capability=${encodeURIComponent(capability)}`, relayUrl)); if (!response.ok) throw new Error("Pairing has not been approved"); const result = await response.json() as { approved: boolean; accountId: string | null; keyVersion?: number; wrappedAccountKey: string | null }; if (!result.approved || !result.accountId || !result.wrappedAccountKey) throw new Error("Pairing is still awaiting Windows approval"); const { unlockWrappedAccountKey } = await import("@nosh/crypto"); return { accountId: result.accountId, accountKey: await unlockWrappedAccountKey(result.wrappedAccountKey, keys), keyVersion: result.keyVersion ?? 1 }; }
export async function unlockPairedVault(vault: Vault, password: string): Promise<PairedVault> { const { decryptVault } = await import("@nosh/crypto"); const value = await decryptVault(vault, password) as unknown as PairedVault; if (!value.accountId || !value.accountKey || !value.signingSecretKey) throw new Error("Device pairing is incomplete"); return value; }
function decode(value: string): Uint8Array { const base64 = value.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(value.length / 4) * 4, "="); const binary = atob(base64); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); }
function encode(value: Uint8Array): string { return btoa(String.fromCharCode(...value)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
