import { createId } from "@nosh/core";
import { EventStore } from "@nosh/persistence";
import { schemaUri, type EventDraft, type JsonValue, type RuntimeInstruction } from "@nosh/wire";
import { mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { OrchestrationRuntime } from "./index.js";

const directories: string[] = [];
const stores: EventStore[] = [];
afterEach(() => { for (const store of stores.splice(0)) try { store.close(); } catch {} for (const directory of directories.splice(0)) rmSync(directory, { recursive: true, force: true }); });

class Sessions {
  readonly active = new Map<string, Session>();
  readonly prompts: string[] = [];
  delay = 0;
  omitDraft = false;
  failMessage = "";
  extraTools: string[] = [];
  draft: ((episodeType: string) => JsonValue) | undefined;
  constructor(private readonly append: (draft: EventDraft) => void) {}
  async start(options: Session) { const value = { ...options, piSessionId: `pi-${options.agentId}-${this.active.size}`, status: "idle" as const, currentTool: null, startedAt: new Date().toISOString(), lastEventAt: new Date().toISOString() }; this.active.set(options.agentId, value); return value; }
  async prompt(agentId: string, prompt: string) { const session = this.active.get(agentId)!; this.prompts.push(prompt); if (this.delay) await new Promise((resolve) => setTimeout(resolve, this.delay)); const type = (/episode-draft of type ([a-z0-9_.:-]+)/.exec(prompt)?.[1] ?? "episode_test").replace(/\.$/, ""); this.append(event(session, "agent.started", {})); if (this.failMessage) throw new Error(this.failMessage); for (const toolName of this.extraTools) this.append(event(session, "agent.tool_completed", { toolName })); if (!this.omitDraft) { this.append(event(session, "record.submitted", this.draft?.(type) ?? { $schema: schemaUri("episode-draft"), schemaVersion: 1, episodeType: type, summary: `summary ${session.taskId}`, facts: [], decisions: [], artifactIds: [], evidenceIds: [], changedFiles: [], unresolvedQuestions: [], recommendedNextActions: [] })); this.append(event(session, "agent.tool_completed", { toolName: "nosh_episode_submit" })); } this.append(event(session, "agent.completed", { message: "done", modelTokens: 12 })); }
  async followUp(_agentId: string, _message: string) {}
  async steer(_agentId: string, _message: string) {}
  async abort(_agentId: string) {}
  stop(agentId: string) { this.active.delete(agentId); }
  inspect() { return [...this.active.values()].map((session) => ({ ...session, role: session.role, piSessionId: `pi-${session.agentId}`, status: "idle" as const, currentTool: null, startedAt: new Date().toISOString(), lastEventAt: new Date().toISOString() })); }
}

type Session = { projectId: string; missionId: string | null; directionId: string | null; autoresearchId: string | null; experimentId: string | null; runId: string | null; jobId: string | null; taskId: string | null; agentId: string; role: "nosh" | "mission_director" | "research_director" | "librarian_researcher" | "general_worker" | "reviewer"; cwd: string; packagePath: string };

describe("typed orchestration runtime", () => {
  test("runs parallel threads, awaits episodes, composes context, and survives Pi rotation/restart", async () => {
    const fixture = setup(); const first = open(fixture.projectId, "first"); const second = open(fixture.projectId, "second"); await Promise.all([fixture.runtime.execute(first), fixture.runtime.execute(second)]); fixture.sessions.delay = 20;
    const stepOne = fixture.runtime.execute(step(fixture.projectId, first.threadId, "one")); const stepTwo = fixture.runtime.execute(step(fixture.projectId, second.threadId, "two"));
    const awaited = await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_AWAIT", threadIds: [first.threadId, second.threadId], policy: "all", minimumCount: null, deadline: null })); await Promise.all([stepOne, stepTwo]);
    expect((awaited as { episodeIds: string[] }).episodeIds).toHaveLength(2); const episodes = fixture.runtime.episodes(fixture.projectId); expect(episodes).toHaveLength(2); expect(episodes.map((entry) => entry.value.usage.modelTokens)).toEqual([12, 12]); expect(episodes.map((entry) => entry.value.usage.toolCalls)).toEqual([1, 1]); expect(fixture.runtime.trace(fixture.projectId, episodes[0]!.entityId).map((item) => item.type)).toContain("agent.completed");
    await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_COMPOSE", targetThreadId: first.threadId, episodeIds: [episodes.find((item) => item.value.threadId === second.threadId)!.entityId] })); await fixture.runtime.execute(step(fixture.projectId, first.threadId, "composed")); expect(fixture.sessions.prompts.at(-1)).toContain("Selected prior episodes");
    const databasePath = fixture.databasePath; fixture.store.close(); const store = new EventStore(databasePath); stores.push(store); const sessions = new Sessions((draft) => store.append(draft)); const restarted = runtime(fixture.projectId, fixture.root, store, sessions); const rotated = await restarted.rotate(fixture.projectId, first.threadId, `rotate-${crypto.randomUUID()}`); expect(rotated.sessionHistory).toHaveLength(2); expect(restarted.episodes(fixture.projectId)).toHaveLength(3); store.close();
  });

  test("applies dynamic skills, bounded programs, foreground forks, and causal suppression hooks", async () => {
    const fixture = setup(); const skillId = createId("skl"); fixture.runtime.registerSkill(fixture.projectId, { $schema: schemaUri("skill-manifest"), schemaVersion: 1, skillId, name: "skill_check", version: "1.0.0", description: "Check a focused output", activation: { roles: ["general_worker"], requiredCapabilities: ["action_write"], episodeTypes: [] }, promptFragment: "Follow the dynamic skill checklist.", permittedTools: ["nosh_episode_submit"], inputEpisodeTypes: [], outputEpisodeType: "episode_test", executionMode: "prompt", programId: null, preflightChecks: ["check_budget"], postflightChecks: ["check_episode"] }, `skill-${crypto.randomUUID()}`);
    const opened = open(fixture.projectId, "skilled", { skillIds: [skillId], capabilities: ["action_write"] }); await fixture.runtime.execute(opened); await fixture.runtime.execute(step(fixture.projectId, opened.threadId, "use skill")); expect(fixture.sessions.prompts.at(-1)).toContain("Follow the dynamic skill checklist"); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).value.activeSkillIds).toEqual([]);
    const programId = createId("prg"); const programInstruction = base(fixture.projectId, { operation: "THREAD_PAUSE", threadId: opened.threadId, reason: "program pause" }); fixture.runtime.registerProgram(fixture.projectId, { $schema: schemaUri("orchestration-program"), schemaVersion: 1, programId, name: "program_pause", version: "1.0.0", startStepId: "step_pause", maximumSteps: 2, maximumWallClockSeconds: 30, maximumModelTokens: 1_000, maximumToolCalls: 20, state: { namespace: "state_pause", schema: { paused: "json" }, initial: { paused: null } }, steps: [{ stepId: "step_pause", instruction: programInstruction, guard: { ref: "paused", operator: "equals", value: null }, background: false, outputStateKey: "paused", nextStepId: null, failureStepId: null }] }, `program-${crypto.randomUUID()}`); await Promise.all([fixture.runtime.runProgram(fixture.projectId, programId), fixture.runtime.runProgram(fixture.projectId, programId)]); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).state).toBe("paused"); expect(fixture.runtime.programStates(fixture.projectId)[0]!.value.status).toBe("completed"); expect(fixture.runtime.programStates(fixture.projectId)[0]!.value.executionCount).toBe(1); await fixture.runtime.execute(base(fixture.projectId, { operation: "STOP", threadId: null, programId, reason: "operator stop" })); expect(fixture.runtime.programStates(fixture.projectId)[0]!.value.status).toBe("stopped");
    const backgroundThread = open(fixture.projectId, "program background"); await fixture.runtime.execute(backgroundThread); const backgroundProgramId = createId("prg"); fixture.sessions.delay = 20; fixture.runtime.registerProgram(fixture.projectId, { $schema: schemaUri("orchestration-program"), schemaVersion: 1, programId: backgroundProgramId, name: "program_background", version: "1.0.0", startStepId: "step_background", maximumSteps: 2, maximumWallClockSeconds: 30, maximumModelTokens: 1_000, maximumToolCalls: 20, state: { namespace: "state_background", schema: {}, initial: {} }, steps: [{ stepId: "step_background", instruction: step(fixture.projectId, backgroundThread.threadId, "background action"), guard: null, background: true, outputStateKey: null, nextStepId: null, failureStepId: null }] }, `program-${crypto.randomUUID()}`); const backgroundResults = await fixture.runtime.runProgram(fixture.projectId, backgroundProgramId); expect(backgroundResults).toHaveLength(1); expect(fixture.runtime.episodes(fixture.projectId).some((entry) => entry.value.threadId === backgroundThread.threadId)).toBe(true); fixture.sessions.delay = 0;
    const fork = { ...open(fixture.projectId, "foreground"), operation: "THREAD_FORK" as const, controllingThreadId: opened.threadId, executionMode: "foreground_fork" as const, parentThreadId: null }; await fixture.runtime.execute(fork); expect(fixture.runtime.hasActiveFork(fixture.projectId, null, null)).toBe(true);
    fixture.runtime.registerHook((instruction) => instruction.operation === "DIRECT_ACTION" ? { assignment: "suppress", reasons: ["controlled experiment"] } : undefined); const suppressed = await fixture.runtime.execute(base(fixture.projectId, { operation: "DIRECT_ACTION", threadId: opened.threadId, action: "action_write", payload: {} })); expect(suppressed).toEqual({ suppressed: true, reasons: ["controlled experiment"] }); expect(fixture.store.projections(fixture.projectId, "runtime_intervention").length).toBeGreaterThan(0); fixture.store.close();
  });

  test("executes direct actions and enforces cancel, stop, and proposer ownership", async () => {
    const fixture = setup(); const actions: string[] = []; const controlled = new OrchestrationRuntime({ storeFor: () => fixture.store, projectFor: () => ({ projectId: fixture.projectId, repositoryRoot: fixture.root }), sessions: fixture.sessions as never, packagePath: fixture.root, directAction: (action) => { actions.push(action); return { action }; } });
    const first = open(fixture.projectId, "owned", { capabilities: ["action_write"] }); const second = open(fixture.projectId, "other"); await controlled.execute(first); await controlled.execute(second);
    expect(await controlled.execute(base(fixture.projectId, { operation: "DIRECT_ACTION", threadId: first.threadId, action: "action_write", payload: { path: "result.json" } }))).toEqual({ result: { action: "action_write" } }); expect(actions).toEqual(["action_write"]);
    await controlled.execute(base(fixture.projectId, { operation: "THREAD_CANCEL", threadId: second.threadId, reason: "no longer needed" })); expect(controlled.thread(fixture.projectId, second.threadId).state).toBe("cancelled");
    const owner = controlled.thread(fixture.projectId, first.threadId).value.currentAgentId!; const intruder = createId("agt"); const unauthorized = { ...step(fixture.projectId, first.threadId, "hijack"), proposedByAgentId: intruder }; await expect(controlled.execute(unauthorized)).rejects.toThrow("not an active Pi session");
    controlled.registerHook((instruction) => instruction.operation === "THREAD_PAUSE" ? { assignment: "replace", reasons: ["try scope escape"], replacement: { ...instruction, operation: "THREAD_CANCEL", threadId: second.threadId, reason: "escaped" } } : undefined); await expect(controlled.execute({ ...base(fixture.projectId, { operation: "THREAD_PAUSE", threadId: first.threadId, reason: "replace" }), proposedByAgentId: owner })).rejects.toThrow("does not control");
    await controlled.execute({ ...base(fixture.projectId, { operation: "STOP", threadId: first.threadId, programId: null, reason: "done" }), proposedByAgentId: owner }); expect(controlled.thread(fixture.projectId, first.threadId).state).toBe("completed"); fixture.store.close();
  });

  test("fails closed on unknown episode evidence and leaves a durable failed thread", async () => {
    const fixture = setup(); const opened = open(fixture.projectId, "invalid"); await fixture.runtime.execute(opened); fixture.sessions.draft = (episodeType) => ({ $schema: schemaUri("episode-draft"), schemaVersion: 1, episodeType, summary: "invalid reference", facts: [], decisions: [], artifactIds: [createId("art")], evidenceIds: [], changedFiles: [], unresolvedQuestions: [], recommendedNextActions: [] });
    await expect(fixture.runtime.execute(step(fixture.projectId, opened.threadId, "reject unknown evidence"))).rejects.toThrow("unknown record"); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).state).toBe("failed"); expect(fixture.store.operationIntents(fixture.projectId, "failed")).toHaveLength(1); fixture.store.close();
  });

  test("gates successful completion on typed output and persists loud agent failures as failed episodes", async () => {
    const missing = setup(); const first = open(missing.projectId, "missing output"); await missing.runtime.execute(first); missing.sessions.omitDraft = true; await expect(missing.runtime.execute(step(missing.projectId, first.threadId, "must be typed"))).rejects.toThrow("required typed episode-draft"); expect(missing.runtime.episodes(missing.projectId)).toHaveLength(0); missing.store.close();
    const failed = setup(); const second = open(failed.projectId, "agent failure"); await failed.runtime.execute(second); failed.sessions.failMessage = "model transport failed"; await expect(failed.runtime.execute(step(failed.projectId, second.threadId, "fail loudly"))).rejects.toThrow("model transport failed"); expect(failed.runtime.episodes(failed.projectId)[0]!.value.status).toBe("failed"); expect(failed.runtime.thread(failed.projectId, second.threadId).state).toBe("failed"); failed.store.close();
  });

  test("rejects malformed programs, duplicate execution, skill policy widening, and budget overruns", async () => {
    const fixture = setup(); const opened = open(fixture.projectId, "adversarial", { budget: { maximumToolCalls: 20, maximumModelTokens: 1_000, maximumWallClockSeconds: 120 } }); await fixture.runtime.execute(opened); const instruction = step(fixture.projectId, opened.threadId, "once only"); const before = fixture.sessions.prompts.length; await Promise.all([fixture.runtime.execute(instruction), fixture.runtime.execute(instruction)]); expect(fixture.sessions.prompts.length - before).toBe(1);
    const sharedSkillId = createId("skl"); const firstProjectSkill = { ...skill(fixture.projectId, ["nosh_episode_submit"]), skillId: sharedSkillId, promptFragment: "Project one skill." }; const otherProjectSkill = { ...firstProjectSkill, promptFragment: "Project two skill." }; fixture.runtime.registerSkill(fixture.projectId, firstProjectSkill, `skill-${crypto.randomUUID()}`); fixture.runtime.registerSkill(createId("prj"), otherProjectSkill, `skill-${crypto.randomUUID()}`); await fixture.runtime.execute({ ...step(fixture.projectId, opened.threadId, "project isolation"), skillIds: [sharedSkillId] }); expect(fixture.sessions.prompts.at(-1)).toContain("Project one skill.");
    const invalidProgram = { $schema: schemaUri("orchestration-program"), schemaVersion: 1, programId: createId("prg"), name: "invalid_program", version: "1.0.0", startStepId: "missing", maximumSteps: 1, maximumWallClockSeconds: 1, maximumModelTokens: 1, maximumToolCalls: 1, state: { namespace: "invalid_state", schema: {}, initial: {} }, steps: [{ stepId: "only_step", instruction: {}, guard: null, background: false, outputStateKey: null, nextStepId: null, failureStepId: null }] }; expect(() => fixture.runtime.registerProgram(fixture.projectId, invalidProgram, `invalid-${crypto.randomUUID()}`)).toThrow();
    const firstSkill = skill(fixture.projectId, ["nosh_episode_submit"]); const secondSkill = skill(fixture.projectId, ["nosh_episode_submit", "action_write"]); fixture.runtime.registerSkill(fixture.projectId, firstSkill, `skill-${crypto.randomUUID()}`); fixture.runtime.registerSkill(fixture.projectId, secondSkill, `skill-${crypto.randomUUID()}`); const policyThread = open(fixture.projectId, "policy", { skillIds: [firstSkill.skillId, secondSkill.skillId] }); await fixture.runtime.execute(policyThread); fixture.sessions.extraTools = ["action_write"]; await expect(fixture.runtime.execute(step(fixture.projectId, policyThread.threadId, "must satisfy both policies"))).rejects.toThrow("Skill tool policy rejected");
    fixture.sessions.extraTools = []; const small = open(fixture.projectId, "small budget", { budget: { maximumToolCalls: 20, maximumModelTokens: 5, maximumWallClockSeconds: 120 } }); await fixture.runtime.execute(small); await expect(fixture.runtime.execute(step(fixture.projectId, small.threadId, "exceed budget"))).rejects.toThrow("model-token budget"); expect(fixture.runtime.episodes(fixture.projectId).find((entry) => entry.value.threadId === small.threadId)?.value.status).toBe("failed"); fixture.store.close();
  });

  test("pauses at an in-flight Episode boundary and preserves terminal thread states", async () => {
    const fixture = setup(); const opened = open(fixture.projectId, "pause boundary"); await fixture.runtime.execute(opened); fixture.sessions.delay = 40; const running = fixture.runtime.execute(step(fixture.projectId, opened.threadId, "finish before pausing")); await new Promise((resolve) => setTimeout(resolve, 10)); const child = { ...open(fixture.projectId, "in-flight child"), operation: "THREAD_FORK" as const, controllingThreadId: opened.threadId, executionMode: "foreground_fork" as const, parentThreadId: null }; await fixture.runtime.execute(child); await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_PAUSE", threadId: opened.threadId, reason: "operator boundary" })); await running; expect(fixture.runtime.thread(fixture.projectId, opened.threadId).state).toBe("paused"); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).value.childThreadIds).toContain(child.threadId); fixture.sessions.delay = 0; await expect(fixture.runtime.execute(step(fixture.projectId, opened.threadId, "blocked"))).rejects.toThrow("foreground fork"); await fixture.runtime.execute(base(fixture.projectId, { operation: "STOP", threadId: child.threadId, programId: null, reason: "fork done" })); await fixture.runtime.execute(step(fixture.projectId, opened.threadId, "resume")); await fixture.runtime.execute(base(fixture.projectId, { operation: "STOP", threadId: opened.threadId, programId: null, reason: "done" })); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).state).toBe("completed"); await expect(fixture.runtime.execute(step(fixture.projectId, opened.threadId, "must not reopen"))).rejects.toThrow("cannot step"); expect(fixture.runtime.thread(fixture.projectId, opened.threadId).state).toBe("completed"); fixture.store.close();
  });

  test("implements first, minimum-count, and deadline joins without returning a stale Episode", async () => {
    const fixture = setup(); const ready = open(fixture.projectId, "ready"); const slow = open(fixture.projectId, "slow"); await Promise.all([fixture.runtime.execute(ready), fixture.runtime.execute(slow)]); const readyResult = await fixture.runtime.execute(step(fixture.projectId, ready.threadId, "ready result")) as { episode: { episodeId: string } }; fixture.sessions.delay = 50; const slowRun = fixture.runtime.execute(step(fixture.projectId, slow.threadId, "slow result")); const first = await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_AWAIT", threadIds: [ready.threadId, slow.threadId], policy: "first_success", minimumCount: null, deadline: null })) as { episodeIds: string[] }; expect(first.episodeIds).toEqual([readyResult.episode.episodeId]); const minimum = await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_AWAIT", threadIds: [ready.threadId, slow.threadId], policy: "minimum_count", minimumCount: 1, deadline: null })) as { episodeIds: string[] }; expect(minimum.episodeIds).toEqual([readyResult.episode.episodeId]); await slowRun; const secondSlowRun = fixture.runtime.execute(step(fixture.projectId, slow.threadId, "new slow result")); const timed = await fixture.runtime.execute(base(fixture.projectId, { operation: "THREAD_AWAIT", threadIds: [slow.threadId], policy: "deadline", minimumCount: null, deadline: new Date(Date.now() + 10).toISOString() })) as { episodeIds: string[] }; expect(timed.episodeIds).toEqual([]); await secondSlowRun; fixture.store.close();
  });
});

function setup() { const root = join(tmpdir(), `nosh-runtime-${crypto.randomUUID()}`); mkdirSync(root); directories.push(root); const projectId = createId("prj"); const databasePath = join(root, "project.sqlite"); const store = new EventStore(databasePath); stores.push(store); const sessions = new Sessions((draft) => store.append(draft)); return { root, projectId, databasePath, store, sessions, runtime: runtime(projectId, root, store, sessions) }; }
function runtime(projectId: string, root: string, store: EventStore, sessions: Sessions) { return new OrchestrationRuntime({ storeFor: () => store, projectFor: () => ({ projectId, repositoryRoot: root }), sessions: sessions as never, packagePath: root }); }
function base(projectId: string, operation: Record<string, JsonValue>): RuntimeInstruction { return { $schema: schemaUri("runtime-instruction"), schemaVersion: 1, instructionId: createId("ins"), projectId, idempotencyKey: `test-${crypto.randomUUID()}`, proposedByAgentId: null, issuedAt: new Date().toISOString(), ...operation } as RuntimeInstruction; }
function open(projectId: string, purpose: string, overrides: { skillIds?: string[]; capabilities?: string[]; budget?: { maximumToolCalls: number; maximumModelTokens: number; maximumWallClockSeconds: number } } = {}) { return base(projectId, { operation: "THREAD_OPEN", threadId: createId("thr"), taskId: createId("tsk"), initialAgentId: null, ownerScope: { missionId: null, directionId: null, autoresearchId: null, experimentId: null, graphNodeId: null }, role: "general_worker", purpose, executionMode: "background", parentThreadId: null, inputRefs: [], skillIds: overrides.skillIds ?? [], capabilities: overrides.capabilities ?? [], budget: overrides.budget ?? { maximumToolCalls: 20, maximumModelTokens: 1_000, maximumWallClockSeconds: 120 } }) as Extract<RuntimeInstruction, { operation: "THREAD_OPEN" }>; }
function step(projectId: string, threadId: string, objective: string) { return base(projectId, { operation: "THREAD_STEP", threadId, objective, expectedEpisodeType: "episode_test", inputRefs: [], skillIds: [] }); }
function skill(_projectId: string, permittedTools: string[]) { return { $schema: schemaUri("skill-manifest"), schemaVersion: 1 as const, skillId: createId("skl"), name: `skill_${crypto.randomUUID().replaceAll("-", "")}`, version: "1.0.0", description: "Adversarial policy fixture", activation: { roles: ["general_worker" as const], requiredCapabilities: [], episodeTypes: ["episode_test"] }, promptFragment: "Apply the policy fixture.", permittedTools, inputEpisodeTypes: [], outputEpisodeType: "episode_test", executionMode: "prompt" as const, programId: null, preflightChecks: [], postflightChecks: [] }; }
function event(session: Session, type: string, payload: JsonValue): EventDraft { return { $schema: schemaUri("event"), schemaVersion: 1, retention: "persistent", type, source: "fixture", scope: { projectId: session.projectId, missionId: session.missionId, directionId: session.directionId, autoresearchId: session.autoresearchId, experimentId: session.experimentId, runId: session.runId, jobId: session.jobId, agentId: session.agentId }, correlationId: session.taskId, causationId: null, payload }; }
