import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ArtifactStore, ClaimEvidenceGraph, appendCanonicalJsonl, recoverJsonl } from "./index.js";

describe("scientific evidence integrity", () => {
  it("addresses artifacts by bytes and retains negative evidence", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-artifacts-")); try { const source = join(directory, "result.json"); writeFileSync(source, "{\"negative\":true}\n"); const store = new ArtifactStore(join(directory, "store")); const artifact = store.add({ artifactId: "art_1", projectId: "prj_1", kind: "evaluation", mediaType: "application/json", sourcePath: source, retentionClass: "negative_evidence" }); expect(store.resolve("art_1").contentHash).toBe(artifact.contentHash); expect(store.cleanup(["negative_evidence"])).toHaveLength(1); } finally { rmSync(directory, { recursive: true, force: true }); } });
  it("flags unsupported claims and rejects derivation cycles", () => { const graph = new ClaimEvidenceGraph(); graph.addEvidence({ evidenceId: "evd_1", statement: "negative", polarity: "contradicts", sourceRefs: [{ refType: "run", refId: "run_1", locator: "/metric" }], evaluationContractHash: "hash", limitations: [], reviewed: true }); graph.addEvidence({ evidenceId: "evd_2", statement: "analysis", polarity: "qualifies", sourceRefs: [{ refType: "artifact", refId: "art_1", locator: "/analysis" }], evaluationContractHash: "hash", limitations: [], reviewed: true }); graph.derive("evd_1", "evd_2"); expect(() => graph.derive("evd_2", "evd_1")).toThrow("cycle"); graph.addClaim({ claimId: "clm_1", text: "positive claim", status: "supported", supportingEvidenceIds: [], contradictingEvidenceIds: ["evd_1"], qualifyingEvidenceIds: [], limitations: [], paperLocations: ["docs/paper.md#results"] }); expect(graph.audit()).toContainEqual({ claimId: "clm_1", issue: "no_reviewed_support" }); });
  it("repairs a partial trailing JSONL line", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-jsonl-")); try { const path = join(directory, "results.jsonl"); appendCanonicalJsonl(path, { id: 1 }); writeFileSync(path, "{\"partial\":", { flag: "a" }); expect(recoverJsonl(path)).toEqual([{ id: 1 }]); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
