import { mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ArtifactStore, appendCanonicalJsonl, recoverJsonl } from "./index.js";

describe("scientific evidence integrity", () => {
  it("addresses artifacts by bytes and retains negative evidence", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-artifacts-")); try { const source = join(directory, "result.json"); writeFileSync(source, "{\"negative\":true}\n"); const store = new ArtifactStore(join(directory, "store")); const input = { artifactId: "art_1", projectId: "prj_1", kind: "evaluation", mediaType: "application/json", sourcePath: source, retentionClass: "negative_evidence" as const }; const artifact = store.add(input); expect(store.resolve("art_1").contentHash).toBe(artifact.contentHash); expect(store.add(input).version).toBe(artifact.version); expect(store.cleanup(["negative_evidence"])).toHaveLength(1); writeFileSync(source, "{\"negative\":false}\n"); expect(store.add(input).version).toBe(artifact.version + 1); } finally { rmSync(directory, { recursive: true, force: true }); } });
  it("repairs a partial trailing JSONL line", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-jsonl-")); try { const path = join(directory, "results.jsonl"); appendCanonicalJsonl(path, { id: 1 }); writeFileSync(path, "{\"partial\":", { flag: "a" }); expect(recoverJsonl(path)).toEqual([{ id: 1 }]); } finally { rmSync(directory, { recursive: true, force: true }); } });
  it.skipIf(process.platform === "win32")("rejects linked artifact sources", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-linked-artifact-")); try { const source = join(directory, "source.json"); const linked = join(directory, "linked.json"); writeFileSync(source, "{}\n"); symlinkSync(source, linked); const store = new ArtifactStore(join(directory, "store")); expect(() => store.add({ artifactId: "art_linked", projectId: "prj_1", kind: "evaluation", mediaType: "application/json", sourcePath: linked, retentionClass: "negative_evidence" })).toThrow(/symlink|reparse/i); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
