import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { exportPaper, initializePaperWorkspace } from "./paper.js";

describe("paper export", () => {
  it("creates a canonical workspace and reproducible LaTeX source", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-paper-")); try { initializePaperWorkspace(directory, "Test Paper"); const manifest = exportPaper(join(directory, "docs", "paper.md"), join(directory, "docs", "paper.bib"), join(directory, "build", "paper")); expect(readFileSync(manifest.latexPath, "utf8")).toContain("\\title{Test Paper}\\maketitle"); expect(manifest.sourceHash).toMatch(/^sha256:[0-9a-f]{64}$/); expect(manifest.command).toEqual(["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", "paper.tex"]); } finally { rmSync(directory, { recursive: true, force: true }); } }, 30_000);
  it("renders pipe tables as aligned tabular instead of review-required comments", () => { const directory = mkdtempSync(join(tmpdir(), "nosh-paper-table-")); try { initializePaperWorkspace(directory, "Table Paper"); const markdownPath = join(directory, "docs", "paper.md"); writeFileSync(markdownPath, ["# Table Paper", "", "| `threshold` | score | note |", "| ---: | ---: | :---: |", "| 0.6 | 0.87 | pass |", "", "After."].join(String.fromCharCode(10))); const manifest = exportPaper(markdownPath, join(directory, "docs", "paper.bib"), join(directory, "build", "paper")); const tex = readFileSync(manifest.latexPath, "utf8"); expect(tex).toContain("\\begin{tabularx}{\\linewidth}{rrc}"); expect(tex).toContain("\\texttt{threshold} & score & note \\\\"); expect(tex).toContain("0.6 & 0.87 & pass \\\\"); expect(tex).not.toContain("TABLE_REVIEW_REQUIRED"); expect(manifest.warnings.some((warning) => warning.includes("table"))).toBe(false); } finally { rmSync(directory, { recursive: true, force: true }); } }, 30_000);
});
