import { id, observedVersionsSchema, schemaUri, schemaVersion, sha256Digest, templateVersion, timestamp } from "./common.js";
import { jsonValueSchema } from "./json.js";
import { z } from "zod";

const ref = z.string().regex(/^[a-z][a-z0-9]*_[a-z0-9][a-z0-9.:-]*$/).max(128);
const text = z.string().min(1).max(4000);
const strings = z.array(z.string().min(1).max(2000)).max(200);
const refs = z.array(ref).max(500);
const jsonObject = z.record(z.string(), jsonValueSchema);
const disposition = z.enum(["supported", "refuted", "inconclusive"]);

export const schemaLockSchema = z.object({ $schema: z.literal(schemaUri("schema-lock")), schemaVersion, noshVersion: z.string(), wirePackageVersion: z.string(), templateBundleVersion: z.string(), schemaDigest: sha256Digest, migrationsApplied: refs, updatedAt: timestamp }).strict();
export const projectRootSchema = z.object({ $schema: z.literal(schemaUri("project-root")), schemaVersion, projectId: id("prj"), activeProjectContractVersion: z.number().int().positive(), activeProjectContractPath: z.string(), operationalDatabaseId: ref, defaultBranch: z.string(), latestPersistentSequence: z.number().int().nonnegative(), updatedAt: timestamp }).strict();
export const projectContractSchema = z.object({
  $schema: z.literal(schemaUri("project-contract")), schemaVersion, templateVersion, projectId: id("prj"), contractVersion: z.number().int().positive(), workingTitle: text, domainTags: strings,
  northStar: z.object({ goalId: ref, question: text, contributionType: ref, decisionUse: text }).strict(), scope: z.object({ included: strings, excluded: strings }).strict(), datasets: z.array(jsonObject), licensingConstraints: strings,
  computeEnvelope: z.object({ maximumGpuHours: z.number().nonnegative(), maximumDiskBytes: z.number().int().nonnegative(), allowedHardwareClasses: strings }).strict(),
  reproducibilityStandard: z.object({ minimumSeeds: z.number().int().positive(), environmentLockRequired: z.boolean(), immutableEvaluatedCommitRequired: z.boolean(), rawLogsRetained: z.boolean() }).strict(),
  paper: z.object({ intendedVenue: z.string().nullable(), requiredSections: strings, claimPolicy: z.literal("evidence_link_required") }).strict(),
  policies: z.object({ network: ref, privacy: ref, publication: ref, protectedPaths: strings }).strict(), canonicalDefaultBranch: z.string(), createdBy: z.enum(["user", "import"]), createdAt: timestamp, approvedAt: timestamp,
}).strict();

export const missionContractSchema = z.object({
  $schema: z.literal(schemaUri("mission-contract")), schemaVersion, templateVersion, missionId: id("mis"), projectId: id("prj"), predecessorMissionId: id("mis").nullable(), objectiveVersion: z.number().int().positive(), title: text, objective: text, nonObjectives: strings,
  projectAlignment: z.object({ projectGoalId: ref, contribution: text }).strict(), deliverables: z.array(jsonObject).min(1), successCriteria: z.array(jsonObject).min(1), exitProofs: z.array(jsonObject).min(1), startingEvidenceIds: z.array(id("evd")), assumptions: z.array(jsonObject), initialGraphVersion: z.literal(1),
  budgets: z.object({ deadline: timestamp, maximumWallClockSeconds: z.number().int().positive(), maximumModelTokens: z.number().int().positive(), maximumGpuSeconds: z.number().int().nonnegative(), maximumDiskBytes: z.number().int().nonnegative(), maximumExperiments: z.number().int().nonnegative(), maximumConcurrentAgents: z.number().int().positive(), maximumConcurrentGpuJobs: z.number().int().nonnegative() }).strict(),
  approvalBoundaries: jsonObject, pausePolicy: jsonObject, finalReviewRubric: z.array(jsonObject).min(1), approvedBy: z.enum(["user"]), approvedAt: timestamp, contractHash: sha256Digest,
}).strict();

export const missionNodeSchema = z.object({ $schema: z.literal(schemaUri("mission-node")), schemaVersion, missionId: id("mis"), graphVersion: z.number().int().positive(), nodeId: ref, nodeType: z.enum(["literature_review", "reproduction", "research_direction", "autoresearch", "implementation", "dataset", "analysis", "claim_review", "paper_section", "integration", "approval", "synthesis", "final_review"]), title: text, rationale: text, criterionIds: refs, hardDependencyNodeIds: refs, softDependencyNodeIds: refs, inputArtifactIds: z.array(id("art")), expectedOutputKinds: refs, assignedRole: ref, preconditionValidatorIds: refs, postconditionValidatorIds: refs, reviewRubricIds: refs, budget: jsonObject, workspacePolicy: jsonObject, state: z.enum(["pending", "ready", "leased", "working", "postflight", "reviewing", "accepted", "blocked", "failed", "waived", "superseded", "cancelled"]), attempt: z.number().int().nonnegative(), lease: jsonValueSchema.nullable(), createdAt: timestamp }).strict();
export const missionStatusSchema = z.object({ $schema: z.literal(schemaUri("mission-status")), schemaVersion, missionId: id("mis"), objectiveVersion: z.number().int().positive(), graphVersion: z.number().int().positive(), state: z.enum(["draft", "planning", "awaiting_approval", "running", "pausing", "paused", "reviewing", "blocked", "stopping", "completed", "stopped", "failed"]), nodeCounts: jsonObject, criticalPathNodeIds: refs, activeTaskIds: z.array(id("tsk")), activeJobIds: z.array(id("job")), openBlockingDefectIds: refs, budget: jsonObject, focus: jsonObject, latestPersistentSequence: z.number().int().nonnegative(), updatedAt: timestamp }).strict();
export const missionCompletionPacketSchema = z.object({ $schema: z.literal(schemaUri("mission-completion-packet")), schemaVersion, missionId: id("mis"), objectiveVersion: z.number().int().positive(), graphVersion: z.number().int().positive(), completionAttempt: z.number().int().positive(), requiredNodeDisposition: z.array(jsonObject).min(1), criteria: z.array(jsonObject).min(1), deliverableArtifactIds: z.array(id("art")).min(1), claimAudit: z.object({ supportedClaimIds: z.array(id("clm")), qualifiedClaimIds: z.array(id("clm")), contradictedClaimIds: z.array(id("clm")), unresolvedClaimIds: z.array(id("clm")) }).strict(), openDefectIds: refs, policyExceptions: refs, budgetReconciliation: jsonObject, reproducibilityManifestArtifactId: id("art"), directorSummaryArtifactId: id("art"), deterministicPreReview: z.object({ status: z.literal("pass"), validatorRunIds: refs }).strict(), builtAt: timestamp }).strict().superRefine((record, context) => { if (record.claimAudit.unresolvedClaimIds.length || record.openDefectIds.length) context.addIssue({ code: "custom", path: ["openDefectIds"], message: "Mission completion cannot contain unresolved claims or defects" }); });

export const directionContractSchema = z.object({ $schema: z.literal(schemaUri("direction-contract")), schemaVersion, templateVersion, directionId: id("dir"), projectId: id("prj"), missionId: id("mis").nullable(), predecessorDirectionId: id("dir").nullable(), questionId: ref, primaryQuestion: text, decisionUse: text, falsifiability: z.object({ supportingOutcome: text, refutingOutcome: text, inconclusiveOutcome: text }).strict(), projectClaimIds: z.array(id("clm")), scope: jsonObject, evaluationContractId: ref, evaluationContractHash: sha256Digest, baselineExperimentId: ref, integrationBranch: z.string(), initialGraphVersion: z.literal(1), stoppingRules: z.array(jsonObject).min(1), budget: jsonObject, closureRubric: z.array(jsonObject).min(1), createdBy: z.enum(["user", "nosh", "mission_director"]), approvedBy: ref, activatedAt: timestamp, contractHash: sha256Digest }).strict();
export const evaluationContractSchema = z.object({ $schema: z.literal(schemaUri("evaluation-contract")), schemaVersion, evaluationContractId: ref, directionId: id("dir"), contractVersion: z.literal(1), datasets: z.array(jsonObject).min(1), preprocessing: jsonObject, metrics: z.array(jsonObject).min(1), baseline: jsonObject, execution: jsonObject, environment: jsonObject, seedPolicy: jsonObject, statistics: jsonObject, failureRules: jsonObject, requiredArtifacts: refs, frozenAt: timestamp, frozenBy: z.enum(["research_director", "user"]), contractHash: sha256Digest }).strict();
export const directionStatusSchema = z.object({ $schema: z.literal(schemaUri("direction-status")), schemaVersion, directionId: id("dir"), state: z.enum(["draft", "proposed", "active", "paused", "blocked", "reviewing", "closed", "rejected", "stopped"]), graphVersion: z.number().int().positive(), evaluationContractHash: sha256Digest, questionDisposition: z.enum(["unresolved", "supported", "refuted", "inconclusive"]), owningWorkerLogicalId: ref, owningAgentId: id("agt").nullable(), nodeCounts: jsonObject, autoresearchCounts: jsonObject, acceptedFrontierExperimentIds: refs, activeTaskIds: z.array(id("tsk")), activeJobIds: z.array(id("job")), openBlockingDefectIds: refs, remainingUncertaintyIds: refs, budget: jsonObject, latestPersistentSequence: z.number().int().nonnegative(), updatedAt: timestamp }).strict();
export const directionClosurePacketSchema = z.object({ $schema: z.literal(schemaUri("direction-closure-packet")), schemaVersion, directionId: id("dir"), graphVersion: z.number().int().positive(), closureAttempt: z.number().int().positive(), evaluationContractHash: sha256Digest, questionDisposition: disposition, answer: text, acceptedExperimentIds: refs, rejectedExperimentIds: refs, inconclusiveExperimentIds: refs, autoresearchCompletionPacketIds: refs, evidenceIds: z.array(id("evd")).min(1), claimEffects: z.array(jsonObject), failedHypothesisFingerprintIds: refs, limitations: strings, openDefectIds: refs, synthesisArtifactId: id("art"), reproducibilityManifestArtifactId: id("art"), deterministicPreReview: z.object({ status: z.literal("pass"), validatorRunIds: refs }).strict(), builtAt: timestamp }).strict().superRefine((record, context) => { if (record.openDefectIds.length) context.addIssue({ code: "custom", path: ["openDefectIds"], message: "Direction closure cannot contain open defects" }); });

export const autoresearchContractSchema = z.object({ $schema: z.literal(schemaUri("autoresearch-contract")), schemaVersion, templateVersion, autoresearchId: id("ar"), projectId: id("prj"), missionId: id("mis").nullable(), directionId: id("dir").nullable(), invokedByRole: z.enum(["user", "mission_director", "research_director"]), decisionQuestion: text, distinctPurpose: text, hypothesisFamilyTags: strings.min(1), duplicateCheck: jsonObject, evaluationContractId: ref, evaluationContractHash: sha256Digest, rootExperimentId: ref, acceptedFrontierExperimentIds: refs, allowedChangeScopes: strings, forbiddenChangeScopes: strings, variantPolicy: jsonObject, budgets: jsonObject, stopConditions: z.array(jsonObject).min(1), promotionRubricIds: refs, createdAt: timestamp, contractHash: sha256Digest }).strict();
export const experimentProposalSchema = z.object({ $schema: z.literal(schemaUri("experiment-proposal")), schemaVersion, proposalId: ref, autoresearchId: id("ar"), experimentId: id("exp"), parentExperimentId: ref, round: z.number().int().positive(), hypothesis: text, rationale: text, primaryChange: z.object({ category: ref, description: text, expectedFiles: strings }).strict(), expectedEffect: jsonObject, guardrailRisks: strings, novelty: z.object({ ideaFingerprint: sha256Digest, nearestAttemptFingerprint: sha256Digest.nullable(), difference: text, duplicateStatus: z.enum(["distinct", "suspected_duplicate", "approved_replication"] ) }).strict(), evaluationContractHash: sha256Digest, estimatedGpuSeconds: z.number().int().nonnegative(), proposedByAgentId: id("agt"), submittedAt: timestamp }).strict();
export const experimentManifestSchema = z.object({ $schema: z.literal(schemaUri("experiment-manifest")), schemaVersion, experimentId: id("exp"), autoresearchId: id("ar"), proposalId: ref, parentExperimentId: ref, treeDepth: z.number().int().nonnegative(), round: z.number().int().positive(), hypothesis: text, primaryChange: jsonObject, ideaFingerprint: sha256Digest, attemptFingerprint: sha256Digest, branch: z.string(), worktreeId: ref, parentCommit: z.string().min(7), implementationCommit: z.string().min(7), evaluatedCommit: z.string().min(7), evaluationContractHash: sha256Digest, state: z.enum(["proposed", "preparing", "ready", "running", "evaluating", "accepted", "rejected", "inconclusive", "failed", "cancelled"]), runIds: z.array(id("run")), resultRecordSequence: z.number().int().nonnegative(), reviewId: id("rev").nullable(), promotionDecision: z.enum(["promoted", "held", "rejected", "pending"]), artifactIds: z.array(id("art")), createdAt: timestamp, evaluatedAt: timestamp.nullable() }).strict();
export const runManifestSchema = z.object({ $schema: z.literal(schemaUri("run-manifest")), schemaVersion, runId: id("run"), experimentId: id("exp"), evaluationContractHash: sha256Digest, evaluatedCommit: z.string().min(7), seed: z.number().int(), resolvedCommand: z.array(z.string()).min(1), workingDirectory: z.string(), inputArtifactIds: z.array(id("art")), configurationArtifactId: id("art"), environmentManifestArtifactId: id("art"), hardware: jsonObject, jobId: id("job"), state: z.enum(["queued", "running", "succeeded", "failed", "cancelled", "lost"]), metricArtifactId: id("art").nullable(), requiredOutputArtifactIds: z.array(id("art")), startedAt: timestamp, finishedAt: timestamp.nullable() }).strict();
export const experimentResultSchema = z.object({ $schema: z.literal(schemaUri("experiment-result")), schemaVersion, autoresearchId: id("ar"), experimentId: id("exp"), parentExperimentId: ref, branch: z.string(), evaluatedCommit: z.string().min(7), evaluationContractHash: sha256Digest, runIds: z.array(id("run")).min(1), runSetStatus: z.enum(["complete", "partial", "invalid"]), metrics: z.array(jsonObject), guardrails: z.array(jsonObject), comparison: jsonObject, deterministicValidation: z.enum(["pass", "fail"]), reviewId: id("rev").nullable(), reviewVerdict: z.enum(["PASS", "REVISE", "REDESIGN", "BLOCKED"]).nullable(), promotionRecommendation: z.enum(["promote", "hold", "reject"]), promotionDecision: z.enum(["promoted", "held", "rejected"]), artifactIds: z.array(id("art")), attemptFingerprint: sha256Digest, completedAt: timestamp }).strict();
export const autoresearchRoundSchema = z.object({ $schema: z.literal(schemaUri("autoresearch-round")), schemaVersion, autoresearchId: id("ar"), round: z.number().int().positive(), inputFrontierExperimentIds: refs, proposedExperimentIds: refs, evaluatedExperimentIds: refs, promotedExperimentIds: refs, rejectedExperimentIds: refs, reviewId: id("rev"), progressDelta: jsonObject, focusCheck: z.object({ distinctIdeaFamiliesInWindow: z.number().int().nonnegative(), repeatedFingerprintCount: z.number().int().nonnegative(), noProgressCount: z.number().int().nonnegative(), action: z.enum(["continue", "reanchor", "review", "stop"] ) }).strict(), nextRoundPurpose: text, completedAt: timestamp }).strict();
export const autoresearchStatusSchema = z.object({ $schema: z.literal(schemaUri("autoresearch-status")), schemaVersion, autoresearchId: id("ar"), state: z.enum(["draft", "running", "paused", "blocked", "completed", "stopped", "failed"]), evaluationContractHash: sha256Digest, currentRound: z.number().int().nonnegative(), rootExperimentId: ref, acceptedFrontierExperimentIds: refs, activeExperimentIds: refs, activeJobIds: z.array(id("job")), experimentCounts: jsonObject, budget: jsonObject, focus: jsonObject, candidateStopReasons: strings, latestPersistentSequence: z.number().int().nonnegative(), updatedAt: timestamp }).strict();
export const autoresearchCompletionPacketSchema = z.object({ $schema: z.literal(schemaUri("autoresearch-completion-packet")), schemaVersion, completionPacketId: ref, autoresearchId: id("ar"), directionId: id("dir").nullable(), evaluationContractHash: sha256Digest, terminalReason: z.enum(["target_reached", "budget_exhausted", "evidence_saturation", "all_hypotheses_rejected", "contract_invalid", "loop_protection", "owner_stop", "review_invalid"]), budgetUse: jsonObject, tree: jsonObject, decisionAnswer: text, bestExperimentId: ref.nullable(), evidenceIds: z.array(id("evd")), failedHypothesisIds: refs, unresolvedQuestions: strings, synthesisArtifactId: id("art"), deterministicValidation: z.object({ status: z.literal("pass"), validatorRunIds: refs }).strict(), closureReviewId: id("rev"), completedAt: timestamp }).strict();

export const jobResultSchema = z.object({ $schema: z.literal(schemaUri("job-result")), schemaVersion, jobId: id("job"), runId: id("run"), experimentId: id("exp"), state: z.enum(["succeeded", "failed", "cancelled", "lost"]), commandDigest: sha256Digest, evaluatedCommit: z.string().min(7), environmentManifestArtifactId: id("art"), startedAt: timestamp, finishedAt: timestamp, durationSeconds: z.number().int().nonnegative(), exit: jsonObject, resourceUse: jsonObject, metricArtifactId: id("art").nullable(), logArtifactIds: z.array(id("art")), checkpointArtifactIds: z.array(id("art")), recovery: jsonObject, resultDigest: sha256Digest }).strict();
export const artifactSchema = z.object({ $schema: z.literal(schemaUri("artifact")), schemaVersion, artifactId: id("art"), projectId: id("prj"), kind: ref, mediaType: z.string(), contentHash: sha256Digest, sizeBytes: z.number().int().nonnegative(), version: z.number().int().positive(), producer: jsonObject, scope: jsonObject, git: jsonObject.nullable(), evaluationContractHash: sha256Digest.nullable(), retentionClass: z.enum(["accepted_evidence", "negative_evidence", "checkpoint", "cache", "temporary"]), remotePreviewPolicy: z.enum(["encrypted_allowed", "local_only", "redacted_only"]), redactionStatus: z.enum(["checked", "redacted", "blocked"]), createdAt: timestamp }).strict();
export const evidenceSchema = z.object({ $schema: z.literal(schemaUri("evidence")), schemaVersion, evidenceId: id("evd"), projectId: id("prj"), evidenceType: ref, statement: text, polarity: z.enum(["supports", "contradicts", "qualifies"]), sourceRefs: z.array(z.object({ refType: ref, refId: ref, locator: text }).strict()).min(1), evaluationContractHash: sha256Digest.nullable(), scopeLimitations: strings, quality: z.object({ status: z.enum(["unreviewed", "reviewed", "rejected"]), reviewId: id("rev").nullable(), confidence: z.enum(["low", "medium", "high"] ) }).strict(), createdByAgentId: id("agt"), createdAt: timestamp }).strict();
export const claimSchema = z.object({ $schema: z.literal(schemaUri("claim")), schemaVersion, claimId: id("clm"), projectId: id("prj"), claimVersion: z.number().int().positive(), text, claimType: ref, status: z.enum(["hypothesis", "under_test", "supported", "partially_supported", "not_supported", "contradicted", "limited", "withdrawn", "qualified"]), supportingEvidenceIds: z.array(id("evd")), contradictingEvidenceIds: z.array(id("evd")), qualifyingEvidenceIds: z.array(id("evd")), limitations: strings, paperLocations: strings, requiredReviewId: id("rev").nullable(), supersedesClaimVersion: z.number().int().positive().nullable(), updatedAt: timestamp }).strict().superRefine((record, context) => { if (!record.supportingEvidenceIds.length && !record.contradictingEvidenceIds.length && !record.qualifyingEvidenceIds.length && !record.limitations.length) context.addIssue({ code: "custom", path: ["limitations"], message: "Claim must have evidence or an explicit limitation" }); });
export const decisionSchema = z.object({ $schema: z.literal(schemaUri("decision")), schemaVersion, decisionId: ref, scopeType: z.enum(["project", "mission", "direction", "autoresearch", "experiment"]), scopeId: ref, decisionType: ref, statement: text, alternatives: strings, rationale: text, evidenceIds: z.array(id("evd")), reviewId: id("rev").nullable(), authority: z.enum(["user", "nosh", "mission_director", "research_director", "reviewer", "daemon"]), actorAgentId: id("agt").nullable(), graphVersion: z.number().int().positive().nullable(), reversible: z.boolean(), supersedesDecisionId: ref.nullable(), createdAt: timestamp }).strict();

export const domainRegistry = {
  [schemaUri("schema-lock")]: schemaLockSchema, [schemaUri("project-root")]: projectRootSchema, [schemaUri("project-contract")]: projectContractSchema,
  [schemaUri("mission-contract")]: missionContractSchema, [schemaUri("mission-node")]: missionNodeSchema, [schemaUri("mission-status")]: missionStatusSchema, [schemaUri("mission-completion-packet")]: missionCompletionPacketSchema,
  [schemaUri("direction-contract")]: directionContractSchema, [schemaUri("evaluation-contract")]: evaluationContractSchema, [schemaUri("direction-status")]: directionStatusSchema, [schemaUri("direction-closure-packet")]: directionClosurePacketSchema,
  [schemaUri("autoresearch-contract")]: autoresearchContractSchema, [schemaUri("experiment-proposal")]: experimentProposalSchema, [schemaUri("experiment-manifest")]: experimentManifestSchema, [schemaUri("run-manifest")]: runManifestSchema, [schemaUri("experiment-result")]: experimentResultSchema, [schemaUri("autoresearch-round")]: autoresearchRoundSchema, [schemaUri("autoresearch-status")]: autoresearchStatusSchema, [schemaUri("autoresearch-completion-packet")]: autoresearchCompletionPacketSchema,
  [schemaUri("job-result")]: jobResultSchema, [schemaUri("artifact")]: artifactSchema, [schemaUri("evidence")]: evidenceSchema, [schemaUri("claim")]: claimSchema, [schemaUri("decision")]: decisionSchema,
} as const;
